kyma-project/lifecycle-manager

README.md
Just changed 'operator' word in one place where I thought it should be changed. OMG my first PR here. Feel free to reject, I probably messed up something.
=> Replaced 'operator' with 'lifecycle-manager' occurrence in docs

operator/config/default/kustomization.yaml, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/prometheus/monitor.yaml, operator/config/rbac/auth_proxy_service.yaml
change all manual occurrences in manager.yaml and all relevant components, e.g. istio / monitoring:
control-plane: controller-manager => app.kubernetes.io/component: kyma-project.io/lifecycle-manager
Also changes common labels in kustomization:
```yaml
commonLabels:
app.kubernetes.io/instance: kcp-lifecycle-manager-main
app.kubernetes.io/name: kcp-lifecycle-manager
app.kubernetes.io/created-by: kustomize
app.kubernetes.io/managed-by: kustomize
app.kubernetes.io/part-of: manual-deployment
```
=> Move Manager Resource to Kustomize Component and change default label for selectors

operator/api/v1alpha1/operator_labels.go, operator/controllers/kyma_controller.go, operator/controllers/setup.go, operator/pkg/module/sync/runner_impl.go, operator/pkg/remote/kyma_synchronization_context.go
If Sync is enabled on the KymaCR then, it will be ensured the needed Labels for the Watcher are set.
=> Add Labels which are needed by Watcher

operator/api/v1alpha1/operator_labels.go, operator/controllers/kyma_controller.go, operator/controllers/kyma_controller_test.go
=> fix: remove ErrNoComponentSpecified to not error out when there are no modules in Kyma

.github/workflows/test.yml
This adds the last necessary job for integration testing with Kyma CLI by providing a job that runs `kyma alpha deploy` for deploying the operators together, but with local sources as we edit the image to be from the PR instead
=> chore: add kyma alpha deploy test

operator/controllers/kyma_controller.go, operator/controllers/module_catalog_controller.go, operator/controllers/suite_test.go, operator/main.go, operator/pkg/catalog/sync.go, operator/pkg/remote/client_cache.go, operator/pkg/remote/kyma_synchronization_context.go
ClientCache is an optimized concurrency-safe in-memory cache based on sync.Map. It is mainly written so that a program that needs multiple Clients in different goroutines can access them without recreation. It does this by holding a concurrency-safe reference map based on an access key (ClientCacheID). It is not optimized for multi-write scenarios, but rather append-only cases where clients are expected to live longer than their calling goroutine.
It thus borrows the same optimizations from it: The ClientCache type is optimized for when the entry for a given key is only ever written once but read many times, as in caches that only grow.
=> feat: introduce (remote) client cache to reduce remote reconciliation latency

operator/config/load_test/kustomization.yaml, operator/controllers/kyma_controller.go, operator/main.go
Introduces a pprof listener endpoint for tracing memory and CPU consumption to use in load tests or debugging
=> feat: include pprof tracing into lifecycle-manager by flag

operator/config/load_test/patches/adjust_resources_in_deployment.yaml, operator/main.go
This introduce 4 flags to configure our burst/bucket client rate limiting in lifecycle manager dynamically and also increases performance test targets to achive >10k cluster scalability
=> chore: configurable rate limit adjustments and increased perf test limits for >10k Clusters

operator/api/v1alpha1/codec/unsafe/codec.go, operator/api/v1alpha1/kyma_types.go, operator/api/v1alpha1/moduletemplate_types.go, operator/api/v1alpha1/webhook_crd_test.go, operator/config/crd/bases/operator.kyma-project.io_kymas.yaml, operator/config/load_test/kustomization.yaml, operator/config/watcher/kustomization.yaml, operator/controllers/kyma_controller_helper_test.go, operator/go.mod, operator/main.go, operator/pkg/channel/lookup.go, operator/pkg/module/common/module.go, operator/pkg/module/parse/template_to_module.go, operator/pkg/module/sync/runner_impl.go
Introduces an unsafe OCM Decoder as controller-runtime does not have inbuilt decoding capabilities of runtime.RawExtension. This circumvents the needs for a cache. Per Reconcile Loop decode will still be called only once. If this still proves to be too much overhead (currently about 40% of reconcile loop, other 40% are spent on reconciling the remote Kyma and 20% are spent on the actual reconciliation loop), we should introduce an explicit generation-based cache in the controller.
=> fix: unsafe decoder for descriptor after webhook

operator/api/v1alpha1/operator_annotations.go, operator/controllers/kyma_controller_helper_test.go, operator/controllers/kyma_controller_remote_sync_test.go, operator/pkg/catalog/remote_catalog.go
This fixes a malbehaving implementation in the catalog sync that was trying to sync moduletemplates based on a label mismatch with generation. As this implementation is based on the assumption that generation incrementations can be precomputed easily (which they cannot, they have to be supported by a hash algorithm for the spec), we want to test wether we are okay with always applying all ModuleTemplates instead. In this scenario, we also calculate a diff, but always apply all ModuleTemplates instead of only applying when there is a label mismatch with the discovered generation.
=> Fix catalog sync gen mismatch by always applying all ModuleTemplates irrespective of generation

api/v1alpha1/operator_labels.go, api/v1alpha1/watcher_types.go, controllers/kyma_controller.go, controllers/kyma_controller_helper_test.go, controllers/kyma_controller_remote_sync_test.go, controllers/kyma_controller_test.go, controllers/kyma_moduleinfo_test.go, controllers/moduletemplate_test.go, controllers/withwatcher/kyma_controller_test.go, controllers/withwatcher/watcher_controller_helper_test.go, pkg/catalog/remote_catalog.go, pkg/remote/kyma_synchronization_context.go, pkg/testutils/utils.go, skr-webhook/templates/deployment.yaml, skr-webhook/values.yaml
Fixes #311 
Changes Proposed:
- Changes Catalog Sync to use `spec.sync.namespace` for all ModuleTemplates if given, otherwise uses Kyma Namespace
- Enforces Namespace if not created based on `spec.sync.namespace` or on Kyma Namespace if sync setting is not set
- Readds `operator.kyma-project.io/pod-restart-trigger` to the helm chart of skr watcher as it was mistakenly removed during the big move to root
WARNING: this adds another roundtrip to lifecycle manager synchronization for the server side apply patch, meaning it has a small performance impact. It could later on be revisited with a better conflict strategy but for now we assume lifecycle manager owns the namespace.
=> Fix namespace sync by enforcing creation of the namespace and using this in catalog sync for module-templates

controllers/kyma_controller.go, controllers/suite_test.go, controllers/withwatcher/suite_with_watcher_test.go, pkg/deploy/chart_manager.go, pkg/deploy/webhook_chart.go, pkg/remote/client.go, pkg/remote/client_cache.go, pkg/remote/client_lookup.go, pkg/remote/cluster_client.go, pkg/remote/context.go, pkg/remote/kyma_synchronization_context.go
Introduces a new Client Abstraction that includes rest config. Also fixes Webhook lookup of SKR clients as it was skipping the cache for the chart installation and removal (was looking up the secret explicitly). Also overrides SKR Rate Limiting Config with KCP values to avoid rate limiting on catalog sync if configured properly.
=> feat: introduce unified client and skr rate limit override

config/samples/component-integration-installed/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
Files was removed with https://github.com/kyma-project/lifecycle-manager/pull/348/files#diff-35bb8ee4aeb31abc92bd1be598b3b94833be5a5acdf7388d015e52f888f3507d
This file is needed for local two cluster setups.
=> Add removed files which is needed for two cluster setups

controllers/kyma_controller.go, controllers/moduletemplate_test.go, go.mod, go.sum, pkg/module/parse/template_to_module.go, pkg/module/sync/runner_impl.go
This PR introduces concurrent SSA for the Manifests generated from the ModuleTemplates and the Kyma CR. Due to this change we also no longer need the "statusUpdateRequired" pattern.
In a follow-up PR it is easily possible now to update the Status Update to SSA as well to decrease possible optimistic lock problems.
It also fixes up the Module Template Test that was touched by https://github.com/kyma-project/lifecycle-manager/pull/358. The test data was changed here to not have a config layer anymore and thus caused issues as the test case was always expecting a config layer. thus the test is now changed to allow empty config layers.
Also Fix https://github.com/kyma-project/lifecycle-manager/issues/362 by introducing a more detailed namespace handling for manifest and spec.data
=> !feat: SSA for module apply / fix namespace handling / fix test data for credSecretSelector

config/samples/component-integration-installed/operator_v1beta1_moduletemplate_kcp-module.yaml, controllers/kyma_controller_helper_test.go, controllers/kyma_controller_remote_sync_test.go, pkg/img/parse.go
**Proposed change(s):**
- Ignore parsing access layers with type `ociRegistry`
=> Introduce ociRegistry access support for module-templates

api/v1beta1/operator_labels.go, pkg/declarative/v2/default_transforms.go, pkg/labels/component_labels.go, pkg/remote/kyma_synchronization_context.go
The naming scheme of `operator.kyma-project.io/owned-by` causes errors during SSA as the naming can get too long:
```
Warning  ServerSideApply  4m1s  declarative.kyma-project.io/events  ServerSideApply failed (after 34.811534ms): patch for clusterrolebindings/istio-manager-rolebinding failed: ClusterRoleBinding.rbac.authorization.k8s.io "istio-manager-rolebinding" is invalid: metadata.labels: Invalid value: "kcp-system__226094f5-ac2a-4ffc-bfd2-1d7d41185286-istio-4034478325": must be no more than 63 characters
```
=> fix: remove bad naming scheme from `operator.kyma-project.io/owned-by`

.github/workflows/test.yml, api/v1alpha1/manifest_conversion.go, api/v1alpha1/manifest_types.go, api/v1beta1/manifest_types.go, internal/manifest/v1beta1/ready_check.go, pkg/declarative/v2/default_transforms.go, pkg/declarative/v2/default_transforms_test.go, pkg/declarative/v2/mock/object.go, pkg/declarative/v2/object.go, pkg/declarative/v2/spec.go, pkg/declarative/v2/test/v1/declarative_test.go, pkg/module/common/module.go
It can happen that the `app.kubernetes.io/component` label key that is added to every object reconciled by the manifest control-loop exceeds 63 characters since it prepends every object name with `manifest-`. Since object names can already be 63 characters long, I removed this prefix. This meant we can directly use the GetName() method and I could remove the method for the ComponentName in the declarative controller.
Additionally this PR adjusts the max Label Size of the CreateModuleName function to 63 (the value required for k8s object names and label keys) instead of 253 (label values) according to DNS1035, as we previously had the wrong validation length configured for module names.
I also noticed that integration tests are no longer waiting for the image build in the github action …
=> fix: DNS1035 Label Key Compliance

flags.go
reduces overall max delay settings for reconcile backoffs as this setting was optimised for 10000 cluster setup which is rarely used in open source and local setup with cli thus reducing reactivity of the system unnecessarily
=> fix: change backoff max reconcile delay from 1000s to 5s

controllers/manifest_controller.go, internal/manifest/v1beta1/client.go, internal/manifest/v1beta1/manifest_controller_test.go, internal/manifest/v1beta1/ready_check_test.go, internal/manifest/v1beta1/suite_test.go, internal/util.go, pkg/declarative/v2/options.go, pkg/declarative/v2/reconciler.go, pkg/declarative/v2/test/v1/declarative_test.go
At the moment, for the performance perspective, we cached remote cluster client, and the cache key is using kyma name, so each module defined under same kyma will shared same cluster client. 
However, if modules target are different, for example, some of them defined in control-plane, some in remote (although in practice, we don't have this scenario), then the client should be different.
The PR fixes this bug by providing a different cache key generation logic.
=> manifest reconciler can't handle different target module managed by same kyma

controllers/manifest_controller.go, internal/manifest/v1beta1/client.go, internal/manifest/v1beta1/manifest_controller_test.go, internal/manifest/v1beta1/parse.go, internal/manifest/v1beta1/ready_check.go, internal/manifest/v1beta1/ready_check_test.go, internal/manifest/v1beta1/spec_resolver.go, internal/manifest/v1beta1/suite_test.go
Related issue: https://github.com/kyma-project/lifecycle-manager/issues/440
The nil point error is due to the KCP in ManifestSpecResolver not being initialized.
=> Fix Private OCI registry authentication crashed Lifecycle-Manager

controllers/kyma_controller.go, controllers/kyma_controller_helper_test.go, internal/declarative/v2/renderer_raw_test.go, internal/declarative/v2/renderer_with_cache_test.go, internal/declarative/v2/ssa_test.go, internal/declarative/v2/test/v1/api.go, internal/declarative/v2/test/v1/declarative_test.go, internal/declarative/v2/test/v1/helper_test.go, internal/declarative/v2/test/v1/suite_test.go, internal/manifest/v1beta1/client.go, internal/manifest/v1beta1/custom_resource.go, internal/manifest/v1beta1/manifest_controller_test.go, internal/manifest/v1beta1/ready_check.go, internal/manifest/v1beta1/ready_check_test.go, internal/manifest/v1beta1/skr_client_lookup.go, internal/manifest/v1beta1/spec_resolver.go, internal/manifest/v1beta1/suite_test.go, pkg/metrics/metrics.go, pkg/status/kyma_helper.go
Description:
* Whenever the expected `skr-domain` annotation or `kyma-project.io/instance-id` label on a Kyma are missing when setting kyma status metric it should not create a warning event rather than just log that
=> Replace warning events when setting metrics by info log

internal/declarative/v2/factory.go
- Remove the unreferenced `DynamicResourceInfo` function
- Remove the `// TODO remove this hack. This is allowing the GetOptions to be serialized.` since that's required for the REST client to talk to the apiserver
Part of #310
=> Revisiting TODOs

config/control-plane/kustomization.yaml, flags.go, main.go
- Added `max-concurrent-kyma-reconciles` flag for the Kyma controller, with value for control-plane: 10
- Added `max-concurrent-manifest-reconciles` flag for the Manifest controller, with value for control-plane: 10
- Added `max-concurrent-watcher-reconciles` flag for the Manifest controller, with default value of 1
Closes #515
=> Increase workqueue workers for KCP

config/samples/component-integration-installed/operator_v1beta1_moduletemplate_kcp-module.yaml, controllers/kyma_controller_helper_test.go, controllers/kyma_controller_remote_sync_test.go, controllers/kyma_controller_test.go, controllers/moduletemplate_test.go, internal/declarative/v2/renderer_raw.go, internal/manifest/v1beta1/manifest_controller_helper_test.go, pkg/status/conditions_test.go
This PR fix the broken tests due to the module template lack of some expected `spec.initKey` fields.
I refactored the "Kyma sync into Remote Cluster" test, previous test expected a label in component descriptor get reset, since currently component descriptor information anyway get from remote, it brings not so much value to detect this behavior, now changed to detect if module template spec get reset.
=> Fix broken tests

config/control-plane/kustomization.yaml, config/default/kustomization.yaml, config/webhook/kustomization.yaml
To prepare for next API upgrade, the admission webhook needs to be updated, `Mutatingwebhookconfigurations` is useless, and we only need `Validatingwebhookconfigurations` for moduletemplate, however, kustomize can't remove those two existing resources automatically. 
In this PR, it removes all admission webhooks, so that in next API upgrade, we can create new resources from scratch to avoid handle deprecated webhook endpoint.
=> Remove admission webhook

config/control-plane/patches/adjust_resources_in_deployment.yaml
Atm, LM in KCP DEV always reach 2000m CPU limit, bring CPU throttling. After run pprof, most CPU time spent on the conversion webhook, which we can't avoid.
This PR increased the CPU limit to 4000m, to see if it can be sufficient for LM to handle for CR conversion.
=> increase cpu limit to 4000 for control plane

controllers/control-plane/control_plane_suite_test.go, controllers/kyma_controller.go, controllers/kyma_controller_helper_test.go, controllers/kyma_controller_remote_sync_test.go, controllers/kyma_controller_test.go, controllers/suite_test.go, controllers/withwatcher/suite_with_watcher_test.go, flags.go, main.go, pkg/module/parse/template_to_module.go, pkg/remote/context.go, pkg/remote/kyma_synchronization_context.go, pkg/remote/remote_catalog.go, pkg/watcher/skr_webhook_manifest_manager.go, pkg/watcher/webhook_chart.go
Introduce a global `sync-namespace` flag that configures target namespace for Kyma and module catalog sync.
This changes previous behavior of taking this namespace from the Kyma object itself.
The `v1beta1` behavior for this was the (now removed) Spec.Sync.Namespace attribute.
- introduce the `sync-namespace` flag
- adjust the logic and tests
=> Add global flag for target sync namespace

controllers/kyma_controller.go
Atm, this info log constantly report unexisting kyma get reconciled, assume it's a bug from controller-runtime or could figure out the root cause at the moment, the current decision is temporarily downgrading to debug level to prevent it flooding log. At least those non exists kyma get into reconciling loop will not process further, hiding this log doesn't bring side effects.
https://github.com/kyma-project/lifecycle-manager/issues/579
=> set deleted kyma log to debug level

config/watcher_local_test/kustomization.yaml, controllers/control-plane/kcp_controller_helper_test.go, controllers/control-plane/kcp_controller_remote_sync_test.go, controllers/kyma_controller.go, pkg/remote/kyma_synchronization_context.go, pkg/remote/kyma_synchronization_context_test.go
Fix invalid sync of the remote Kyma `status.conditions`
- Fix invalid sync of the remote Kyma `status.conditions`
- minor renaming to more readable identifiers
#618
=> Fix invalid remote kyma status sync

internal/manifest/v1beta1/parse.go
This PR introduces an in-memory locking mechanism to avoid parallel writes to the same file when handling raw manifests.
This also ensures there are no `reads` of the file when the `write` is still pending.
All of this is to ensure the read/write consistency of the data.
For any specific file:
1) only a single goroutine may check if the file exists, all other writers/readers must wait
2) only a single goroutine may create the file and write data to it, all other writers/readers must wait
Operation 1) is very fast so though it's performed many times, the additional locking is not expected to impact performance (to be verified).
Operation 2) is slow, but it's executed only once per module version in the Lifecycle-Manager lifetime. It …
=> Fix parallel file cache access

internal/manifest/v1beta1/spec_resolver.go
With current implementation, the credSecretSelector for private oci registry access secret are coming from config layer (which is not used anymore), if the module template doesn't contains config layer, it will failed to get the secret and use default keychain. This PR fixed it by changes to get the credSecretSelector from install layer.
=> Get credSecretSelector from install layer instead of optional config layer

api/v1beta2/moduletemplate_types.go, api/v1beta2/moduletemplate_webhook.go, api/v1beta2/webhook_moduletemplate_crd_validation_test.go, config/load_test/kustomization.yaml, config/load_test/manager_webhook_patch.yaml, config/load_test/webhookcainjection_patch.yaml, controllers/kyma_controller_helper_test.go, controllers/setup.go, internal/manifest/v1beta1/manifest_controller_test.go, internal/manifest/v1beta1/spec_resolver.go, pkg/channel/lookup.go, pkg/module/parse/template_to_module.go, pkg/testutils/utils.go
This PR improved the performance to cache the component descriptor, to avoid repeatly doing heavy CPU intensive yaml unmarshal in  `compdesc.Decode`
check the pprof for detail (click below)
=> introduce component descriptor cache

skr-webhook/resources.yaml
- Warden validation webhook is rejecting images that are not signed from us on skr cluster, so we need to pick a verified image from our registry for the skr-webhook sidecar
* https://github.com/kyma-project/lifecycle-manager/issues/704
=> Fix: skr-webhook sidecar alpine image from internal registry that is signed

config/control-plane/kustomization.yaml
at the moment, with 50 kyma, it's not increase the perfomance (reducing processing latency) too much, in stead increased the CPU usage, lower to 25 can reduce CPU stress.
=> reduce kyma workers

.golangci.yaml, pkg/metrics/metrics.go
- Remove the generation of unused metrics since the cardinality is too high on productive environments
=> Unregister histogram metrics with high cardinality

.github/workflows/e2e-test.yml, config/watcher_local_test/kustomization.yaml, controllers/kyma_test.go, internal/util.go, pkg/testutils/utils.go, tests/e2e_test/Makefile, tests/e2e_test/suite_test.go, tests/e2e_test/watcher_test.go
This PR mainly fixed watcher e2e test by removing envTest CRD overwrites, which will remove the conversion webhook in CRD definition, which makes kyma CR not convert as expected.
It also refactoring exists test cases.
=> fix watcher e2e

.github/workflows/e2e-test.yml, .github/workflows/smoke-test.yml
the build job atm take nearly 5mins to build and publish LM image, this PR increased the timeout to avoid wait job failed due to timeout and have to manually triggering the job.
=> increase wait for image build timeout

.github/workflows/e2e-test.yml
We don't need to do upgrade this one time ubuntu system every time
```
Get:101 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 netstandard-targeting-pack-2.1 amd64 6.0.120-0ubuntu1~22.04.1 [1398 kB]
Preconfiguring packages ...
Fetched 529 MB in 12min 3s (732 kB/s)
```
=> stop upgrade ubuntu every time for e2e test

.github/workflows/e2e-test.yml
- The iterator was called `i` but used as `retry`, thus we never went to into the `else` since retry was always unset and thus lower than `maxRetry`
- Renamed the iterator to `retry` so it is actually counting up
=> Fix wrong naming of iterator

controllers/withwatcher/suite_with_watcher_test.go, main.go, pkg/watcher/skr_webhook_manifest_manager.go, pkg/watcher/webhook_chart.go
LM failed to start with
```
{"level":"ERROR","date":"2023-08-09T13:34:52.133656664Z","logger":"setup","caller":"workspace/main.go:240","msg":"failed to create webhook chart manager","context":{"error":"the cache is not started, can not read objects"},"stacktrace":"main.setupKymaReconciler\n\t/workspace/main.go:240\nmain.setupManager\n\t/workspace/main.go:160\nmain.main\n\t/workspace/main.go:111\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```
=> fix failed to create webhook chart manager

internal/manifest/ready_check.go
If deployment is not ready, should not return error
=> Fix deployment ready error

.github/workflows/e2e-test.yml, internal/manifest/parse.go, internal/manifest/ready_check.go, tests/e2e_test/Makefile, tests/e2e_test/kyma_deletion_test.go, tests/e2e_test/status_propagation_test.go, tests/e2e_test/suite_test.go, tests/e2e_test/utils_test.go, tests/e2e_test/watcher_test.go
- Fix #822 
- Introduce new e2e test to check Status propagation;
- Template operator is being deployed with `--final-state` set to `Warning`; will be checked after template-operator is being enabled; after disabling it should return to Ready
- Use matrix in GH Actions pipeline, to have all e2e scenario tests run in parallel, if there are multiple runners available the pipeline will run faster (7min instead of 11min most of the time, if three runners are available ~5min) + e2e scenarios are fully decoupled
=> Fix propagate warning state

.github/workflows/lint-conventional-prs.yml, .github/workflows/lint-golangci.yml, .github/workflows/test-e2e.yml, .github/workflows/test-smoke.yml
- Unify the titles for the GitHub actions and respective config files
=> chore: Unify GitHub actions names and titles

.github/workflows/lint-markdown-links.yml, .mlc.config.json, README.md, api/README.md, controllers/README.md, docs/README.md, docs/developer-tutorials/local-test-setup.md, docs/modularization.md, docs/technical-reference/api/README.md, docs/technical-reference/api/kyma-cr.md, docs/technical-reference/api/manifest-cr.md, docs/technical-reference/api/moduleTemplate-cr.md, docs/technical-reference/architecture.md, docs/technical-reference/controllers.md, docs/technical-reference/running-modes.md, docs/user-tutorials/01-10-control-plane-quick-start.md, internal/declarative/README.md, internal/manifest/README.md, tests/e2e_test/README.md
Adds a GitHub Action for the Markdown Link checker.
- Creates a GitHub Actions workflow using the [Markdown Link Check](https://github.com/marketplace/actions/markdown-link-check)
- Fixes the links that were broken
=> chore: Add the Markdown Link Checker GitHub action

.github/workflows/lint-golangci.yml, .github/workflows/test-e2e.yml, .github/workflows/test-smoke.yml, .github/workflows/test-unit.yml
- Use GH-Actions instead prow to run `make test`
- Prow job still needs to be cleaned up: https://github.com/kyma-project/test-infra/pull/8896
- Way faster than prow (currently, test takes ~5min + waiting time for free runner)
- Use go 1.21 in GH-Actions, since KLM is written in 1.21
=> chore: Use GH-Action instead prow job for unit testing

tests/smoke_test/module_upgrade/moduletemplate_template_operator_fast.yaml
In this PR, the moduletemplate used for upgrade module smoking test are changed to localBlob, with this change, it make sure LM are possbile to handle both `localOciBlob` and `localblob`
related issue: https://github.com/kyma-project/lifecycle-manager/issues/841
=> test: Introduce localblob for module upgrade test

controllers/kyma_controller/manifest_test.go
Add test case for ModuleTemplate version upgrade in the Manifest CR test suite.
The flow:
- Given a deployed ModuleTempate and Kyma and Manifest CR in a `Ready` state
- When the ModuleTemplate version is updated to a new artifact by setting new version and `raw-manifest` layer hash.
- Then Manifest CR related fields get updated correctly
- Add new test case for kyma controller
#702
=> test: ModuleTemplate version update for Manifest CR suite

.github/dependabot.yml, .github/workflows/lint-markdown-links.yml
- Configure Dependabot's dependency bumps to adhere to the Conventional Commits spec
=> chore(infra): Configure dependabot to adhere to the Conventional Commits spec

controllers/withwatcher/kyma_controller_test.go
Check does not install webhook will collide with other watcher tests which install webhook
=> fix: Remove flaky watcher test condition

tests/e2e_test/Makefile
- Adds a `make e2e-coverage` make target which prints the current acceptance tests coverage:
```
Describe KCP Kyma CR should be deleted successfully when SKR cluster gets deleted
Then Should create empty Kyma CR on remote cluster
By verifying kyma is ready
By verifying remote kyma is ready
It Should remove SKR Cluster
By removing SKR Cluster
By deleting secret
By Kyma should be in Error state
It Should recreate SKR cluster and its secret
By Creating SKR cluster
By Creating Kyma secret
It Kyma should be in Ready state after secret is re-fetched
By Kyma should be in Ready state
It Should delete KCP Kyma
By Deleting KCP Kyma
It Kyma CR should be removed
Describe When KCP Kyma CR deleted
It Should create empty Kyma CR
By verifying kyma is …
```
=> test(e2e): Add Acceptance Criteria report 

Makefile, config/control-plane/kustomization.yaml, config/default/kustomization.yaml, config/default/webhookcainjection_patch.yaml, config/load_test/kustomization.yaml
This PR refines `kustomize` configuration.
The deprecated `vars` is changed to `replacements`.
The change is necessary to switch from kustomize API `v1beta1` to `v1`
- `vars` is changed to `replacements`
See also: #391
=> feat: Kustomize remove vars

pkg/security/internal_test.go, pkg/security/san_pinning.go, pkg/security/san_pinning_test.go
Checkmarx reported potential DDoS via resource-exhaustion around the XFCC header parsing in `pkg/security/san_pinning.go:81` (line number as in the current PR)
This PR does not "fix" the Checkmarx alert - it looks like Checkmarx is complaining about "slice expression" which, on its own, is not leading to any resource exhaustion.
Nevertheless we should protect the code from incjection of big and potentially malicious Certificate data and introduce some limits.
Note to the reviewer: The limits proposed in the PR are arbitrary, AFAIK there are no "hard" values defined for certificate size or a number of SAN of the certificate.
The proposed values seem to be big enough to handle any real scenario considering the Lifecycle-Manager environment.
Changes proposed in this pull …
=> feat: Improve XFCC header parsing in SAN Verification code (Checkmarx)

tests/e2e_test/Makefile
due to github action resources limitation, sometime, e2e test will run longer than the default 10 mins, this PR increased the timeout to 20mins for all tests.
=> chore: Increase timeout for e2e test

.github/workflows/test-e2e.yml, .github/workflows/test-smoke.yml
currently, direct download kubectl from github action seems not working, will download a broken kubectl binary, with error [here](https://github.com/kyma-project/lifecycle-manager/actions/runs/6568311861/job/17851834303?pr=962#step:14:14).
This PR changed the way to download kubectl from apt, from official [document](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management)
=> fix: Change download kubectl from apt

.github/workflows/test-e2e.yml, .github/workflows/test-smoke.yml
only use `actions/setup-go` download go binary
remove already installed packages
```
Reading package lists...
Building dependency tree...
Reading state information...
bash is already the newest version (5.1-6ubuntu1).
make is already the newest version (4.3-4.1build1).
wget is already the newest version (1.21.2-2ubuntu1).
ca-certificates is already the newest version (20230311ubuntu0.22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.14).
git is already the newest version (1:2.42.0-0ppa1~ubuntu22.04.1).
```
=> chore: Download go binary from github action

api/v1beta2/kyma_types.go, api/v1beta2/operator_labels.go, internal/controller/kyma_controller/kyma_test.go, internal/controller/kyma_controller/manifest_test.go, internal/declarative/v2/options.go, pkg/testutils/manifest.go
- Added an integration test for the skip-label on the Manifest
- Renamed the `declarative.kyma-project.io/skip-reconciliation` to `operator.kyma-project.io/skip-reconciliation`
Resolves #937
=> fix: Fix skip reconciliation for Manifest

.github/workflows/test-e2e.yml, .github/workflows/test-smoke.yml, .github/workflows/test-unit.yml, pkg/testutils/utils.go, tests/e2e_test/purge_controller_test.go, tests/e2e_test/purge_metrics_test.go, tests/e2e_test/utils_test.go
github action seems can't use gosumdb to authenticate downloaded module, since the action pipeline is just design for testing purpose, there is no needs to authenticate module. This PR disabled this feature by set a global env value GOSUMDB to `off` based on this [article](https://goproxy.io/docs/GOSUMDB-env.html) 
check failing test [here](https://github.com/kyma-project/lifecycle-manager/actions/runs/6611749687/job/17956816677?pr=976#step:4:7)
additionally, fixed broken e2e test in main.
=> fix broken e2e test and disable gosumdb check

.github/workflows/test-e2e.yml, internal/controller/kyma/metrics/metrics.go, internal/controller/kyma_controller.go, pkg/module/sync/runner_impl.go, tests/e2e_test/kyma_deletion_test.go, tests/e2e_test/kyma_metrics_test.go, tests/e2e_test/module_deletion_test.go, tests/e2e_test/utils_test.go
only use kyma or module name as minimum label for `DeletePartialMatch`.
do the metrics cleanup before remove kyma finalizer.
=> fix: cleanup metrics before kyma finalizer removed

pkg/queue/requeue_intervals.go
- Use the Busy interval set for the `Warning` state
Resolves #1055
=> fix: Use the Busy Interval for the Warning state

pkg/watcher/certificate.go, pkg/watcher/skr_webhook_manifest_manager.go
- Remove Secret only when the secret creation time is before the CA Certificate validity
#1061
=> fix: Remove Secret only when the secret creation time is before the CA Certificate validity

.github/workflows/report-package-metrics.yml
- Creates a GH Action to generate a package metrics report
- The script used for the metric calculation resides in the [qa-toolkit](https://github.com/kyma-project/qa-toolkit/pull/7)
#1089
=> chore(metrics, report): Add a GitHub Action to generate a go package metrics report

.github/workflows/report-package-metrics.yml
Adds explicit Git reference for the target PR. The default setting fetches the `main` branch instead of the PR one.
=> chore(report): Fix the package metrics report GH Action

api/v1beta2/manifest_types.go, config/crd/bases/operator.kyma-project.io_manifests.yaml, pkg/module/common/module.go, pkg/module/parse/template_to_module.go, pkg/module/sync/runner.go, tests/integration/controller/kyma/kyma_test.go, tests/integration/controller/kyma/manifest_test.go
add version as new field to manifest CR, it makes LM to know the version of the module from Manifest CR more straightforward.
It also makes it possible to determine if necessary to update manifest based on the version.
=> feat: Introduce version to manifest CR

pkg/watcher/certificate_manager.go
- Delete SKR Certificate and Secret only if they exist. The current behavior executed the deletion of the certificate/secret even if they are not found which cause infinite reconciliations when the Kyma gets deleted. 
=> fix: Delete SKR Certificate and Secret only if they exist

config/watcher/kustomization.yaml, config/watcher_local_test/kustomization.yaml
- We have a bug in released watcher versions and also e2e is testing against latest, but latest tagging is broken since October
- Remove the watcher img override for e2e test setup: it should use the same img in the tests as the image that is reference and deployed by lifecycle-manager!
=> fix: Set watcher version to last known working

cmd/main.go, internal/controller/manifest_controller.go, internal/controller/setup.go, internal/pkg/metrics/kyma.go
Sets the name of the controller, not by default rely on resource kind, so that it can distinguish controller which reconcile same resource, like kyma_controller and purge_controller, both reconcile Kyma CR.
=> chore: Give each controller a specific name

internal/controller/purge_controller.go
If kyma is not under delete, it's not necessary to requeue it.
=> fix: Stop requeue kyma not deleted for purge controller 

config/grafana/overview.json
- add `controller_runtime_reconcile_total` metrics for `purge`, `watcher`, and `manifest`
- add missing `lifecycle_mgr_requeue_reason_total` metrics
related issue: https://github.com/kyma-project/lifecycle-manager/issues/1102
=> chore: Update Lifecycle Manager Controller Runtime Reconcile Success panel

tests/e2e/module_deletion_test.go
This PR try to fix one flaky test condition, error log [here](https://github.com/kyma-project/lifecycle-manager/actions/runs/7355684613/job/20024832759?pr=1208#step:30:92)
=> fix: Do eventual check before constistent in e2e test 

go.mod, go.sum, pkg/testutils/builder/moduletemplate.go, tests/integration/apiwebhook/webhook_moduletemplate_crd_validation_test.go, tests/integration/controller/kyma/kyma_module_channel_test.go, tests/integration/controller/kyma/manifest_test.go
- bump github.com/open-component-model/ocm from 0.4.0 to 0.5.0
- fix breaking changes
- Remove `v3alpha1.SchemaVersion` since `v3alpha1.SchemaVersion = v3alpha1.GroupVersion` in version 0.5.0
=> chore: bump github.com/open-component-model/ocm from 0.4.0 to 0.5.0

internal/controller/purge_controller.go, internal/pkg/metrics/purge.go
- In the team we agreed on using logf.FromContext instead of passing the logger as parameter
=> refactor: Use logger from context instead

config/control-plane/kustomization.yaml
This PR is trying to resolve currently high volume of manifest CR requeue by `manifest_remove_finalizer_in_deleting`.
By increase base delay, it prevent the requeued item get in progressed within short period, currently, the default base delay is 100ms, with the concurrent workers, it will produce huge traffic to API server even with a small amount of items.
=> fix: Increase baseDelay for ExponentialFailureRateLimiter

internal/declarative/v2/ssa.go
This PR intention is to prevent from etcd outages which we observe during secret rotation "peaks", when many SKR secrets are rotated in a short time.
Because of secrets rotation, the Lifecycle-Manager encounters a lot of connection errors and is producing many k8s Events objects.
We found out that some of these events are very big. Reducing the size of events may reduce the stress on etcd to an acceptable level.
Details:
When the secret is rotated, the client we use to access SKR returns an "Unauthorized" error. If this happens on a `patch` request, the error message contains a json-serialized copy of the object being patched.
Because we're putting these error messages into related k8s Event, this results in a very big `Event.message` field. In some cases it exceeds 90KiB. …
=> feat: Suppress "Unauthorized" errors

internal/declarative/v2/client_cache.go, internal/declarative/v2/reconciler.go, internal/manifest/client.go
Observed on DEV: Lifecycle Manager slowly loses connectivity to the SKR's. The error reported in the Manifest CR: `Unauthorized`.
This correlates with short life of the SKR secrets on DEV (100 minutes).
Restarting the LM Pod helps for ~ 100 minutes.
It looks like the clients used in the manifest-controller loop are not refreshed when the secret is rotated/expires.
This PR is an attempt to get more insight into the problem.
On `Unauthorized` error it should invalidate the cached client.
Additional logging is provided for debugging purposes, to be removed once we find the 100% valid fix for the issue.
- Invalidate manifest controller client cache entry upon `Unauthorized` errors
=> feat: Invalidate manifest client cache

internal/controller/purge_controller.go, pkg/util/error.go
This PR is intended to get more insight into the "host not found" errors that appear on DEV.
The error itself looks like a `net.DNSError`. I was unable to reproduce it locally.
The errors are produced by the purge reconciler in the following conditions:
- The SKR cluster is removed
- The SKR secret is removed
- The purge reconciler finalizer is still there (and it's the only finalizer)
- an attempt to catch (and handle) "host not found" error.
=> fix: No such host in purge reconciler

config/grafana/overview.json
- Added container name to max parallel workers metrics dashboard to represent the actual wanted workers we want to have at the dashboard. Because before the metrics from `runtime-monitoring-operator` have been included as well
- 
**Before:**
**After:**
Actuel configured workers
=> fix: Add container name to metrics to exclude metrics which are not related

scripts/migrator_cleanup.sh, scripts/storage_version_migrator.sh
- Add script for storage version migrator deployment
This script deploys the storage version migrator. The migrator deploys its resources in the `kube-system` namespace and it gets triggered every 10 minutes to migrate all resources stored in the etcd to the latest storage version. 
To run the script, use the following command:
`sh ./scripts/storage_version_migrator.sh -c ${CONTEXT}`
where CONTEXT is the context for the cluster where you want to do the API migration 
#1119
=> chore: Add script for storage version migrator

cmd/main.go, internal/controller/kyma_controller.go, internal/controller/manifest_controller.go, internal/declarative/v2/options.go, internal/declarative/v2/reconciler.go, internal/pkg/metrics/common.go, internal/pkg/metrics/kyma.go, internal/pkg/metrics/manifest.go, pkg/queue/requeue_intervals.go, tests/e2e/kyma_metrics_test.go, tests/integration/controller/manifest/custom_resource_check/suite_test.go, tests/integration/controller/manifest/suite_test.go, tests/integration/declarative/declarative_test.go
At the moment, manifest controller only do requeue after for success reconcilation, however for certain cases, if the requeue is unexpected, there is no need to requeue inmediately, which brings unneccesary high amount of requeue event. For example, currently we havemany unexpected `manifest_sync_resources` requeue
This PR address it by introduce another time interval, which reuse `KymaRequeueBusyInterval`, trying to reduce the unexpected requeue numbers.
I also dropped the `CtrlOnSuccess` options, instead introduce the  `queue.RequeueIntervals` directly to manifest Reconciler struct to have fine grained requeue control.
=> feat: Introduce different requeue after interval to control the frequency of unexpected requeue events

pkg/module/sync/runner.go, tests/integration/controller/kyma/kyma_test.go
- Sets Module and Kyma Status to `Warning` if no template was found for a Module
- Adapt Test case
- Fixed indentation for `By`-statements
- The statements related to `By` should be inside the `By` call, otherwise if a test fails, the errr message is missleading
=> feat: Set Kyma Module Status to `Warning` if ModuleTemplate is not found

internal/controller/kyma_controller.go, pkg/util/error.go
- removes the custom `pkg/util/error.go#IsUnauthorized` function and uses `k8s.io/apimachinery/pkg/api/errors#IsUnauthorized` directly instead
=> chore: Unwrap `apierrors.IsUnauthorized`

.github/workflows/test-e2e.yml
- Add `workflow_dispatch` with optional input for Kubernetes version
- Set default version 1.27.10
- Create k3d cluster with either default or optional version for rancher image
- Available rancher imgs can be found here: https://hub.docker.com/r/rancher/k3s/tags
* https://github.com/kyma-project/lifecycle-manager/issues/1295
=> feat: Add k8s version option to e2e

Dockerfile, Makefile, cmd/main.go
Add explicit version embedded in the Lifecycle-Manager binary
- add support for embedding static build version
- always print embedded version at the LM startup
https://github.com/kyma-project/lifecycle-manager/issues/1283
=> feat: Explicit versioning

docs/developer-tutorials/local-test-setup.md
- As we recently aligned to use `1.13.3` cert manager for SRE clusters and e2e tests.
=> docs: Use cert-manager 1.13.3 in local test setup script

internal/declarative/v2/reconciler.go, internal/pkg/metrics/manifest.go, pkg/testutils/metrics.go, tests/e2e/kyma_metrics_test.go
This reverts commit 2b64c7b77d8b58cbc4ce340aef8eb0068dbbd190.
- Reverting the changes because the histogram metric generates huge amount of data 
#1069
=> fix: Revert "feat: Add Manifest Reconcile Duration Metric (#1321)"

cmd/main.go, internal/controller/watcher_controller.go, tests/integration/controller/withwatcher/suite_with_watcher_test.go
- since `Watcher` is now the owner of `VirtualService`, their namespaces are coupled as [K8s requires owner and dependent to be in the same namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications). Hence, we can get rid of the `WatcherVSNamespace` attribute in `WatcherReconciler`
- small follow-up to https://github.com/kyma-project/lifecycle-manager/pull/1349
=> chore: Remove `r.WatcherVSNamespace` from `WatcherReconciler`

internal/controller/purge_controller.go
- fixes an inaccurate log message
- we are removing all finalizers from the resources, not only the purge finalizer
- also added the Kyma name explicitly to the message for easier overview
- could also be seen from the context in the full log, but this will give it at one glance
- follow-up to https://github.com/kyma-project/lifecycle-manager/pull/1392
=> fix: Correct inaccurate log message in purge cleanup

api/v1beta2/kyma_types.go, api/v1beta2/watcher_types.go
- removes inapplicable `kubebuiler:subresource:status` markers from `WatcherStatus` and `KymaStatus`
- kubebuilder assigns a clear meaning behind subresource:status (see [here](https://book.kubebuilder.io/reference/generating-crd.html?highlight=subresource#subresources), and [here](https://book-v1.book.kubebuilder.io/basics/status_subresource))
- the proper `kubebuilder:subresource:status` markers for Kyma and Watcher are [here](https://github.com/kyma-project/lifecycle-manager/blob/main/api/v1beta2/kyma_types.go#L30) and [here](https://github.com/kyma-project/lifecycle-manager/blob/main/api/v1beta2/watcher_types.go#L101)
- applying them again on the `XXXStatus struct` seems unintended and does not yield any changes in the generated …
=> chore: Remove inapplicable `kubebuiler:subresource:status` markers

cmd/main.go, internal/crd/storage_version_dropper.go, internal/crd/storage_version_dropper_test.go
- fixes security scan reports wrt. race conditions for `mgr`, `err` and `setupLog` in the goroutine for dropping stored versions
- aligns the goroutine for scheduling the metrics cleanup with the findings above
- just to be sure, we also wait for the cache to sync
- https://github.com/kyma-project/lifecycle-manager/pull/1403#issuecomment-2031756813
**Comments**
No additional tests as the helpers (`crd.DropStoredVersion`, `kymaMetrics.CleanupNonExistingKymaCrsMetrics`) are already tested. Not sure if worth trying to test the setup in main.
---
Routines execute as expected:
```sh
[...]
{"level":"LEVEL(-2)","date":"2024-04-03T13:49:13.750383456Z","logger":"storage-version-migration","caller":"crd/storage_version_dropp …
```
=> fix: Race condition in drop stored versions

cmd/main.go, internal/pkg/flags/flags.go, internal/pkg/flags/flags_test.go
=> chore: Configure leader election timeout

docs/developer-tutorials/local-test-setup.md
- some minor fixes on the scripts for building KLM and deploying module templates
=> docs: Fix local test setup scripts

config/grafana/status.json
When KLM restarts, then we have multiple Gauges which is not needed.
Before:
After: 
=> chore: Sum count to avoid having multiple gauges

.github/actions/setup-test-clusters/action.yaml, .github/workflows/test-e2e.yaml
- Adds an input to the setup test clusters action allowing to pass additional arguments for the SKR cluster creation
- this is needed for re-use within watcher since in watcher we expose an additional set of ports
- partially resolves kyma-project/lifecycle-manager#1224
=> chore: Add skr args input to setup test clusters action

.github/workflows/test-smoke.yml
- Use the wait for build action in the smoke test GitHub workflow
=> fix: Use the wait for image action for smoke test pipeline

.github/actions/wait-for-image-build/action.yaml
- Should fix flaky tests which time out after migrating to ADO build pipeline
=> chore: Bump 'Wait for image build' `timeoutSeconds` default

.markdownlint.yaml, docs/README.md, docs/developer-tutorials/README.md, docs/developer-tutorials/config-private-registry.md, docs/developer-tutorials/local-test-setup.md, docs/developer-tutorials/prepare-gcr-registry.md, docs/developer-tutorials/provision-cluster-and-registry.md, docs/developer-tutorials/starting-operator-with-webhooks.md, docs/technical-reference/api/README.md, docs/technical-reference/api/changelog.md, docs/technical-reference/api/kyma-cr.md, docs/technical-reference/api/moduleTemplate-cr.md, docs/technical-reference/architecture.md, docs/technical-reference/controllers.md, docs/technical-reference/running-modes.md, docs/user-tutorials/01-10-control-plane-quick-start.md, markdown_heading_capitalization.js
- Add markdownlint to Lifecycle Manager
- Fix linting issues
See also https://github.com/kyma-project/kyma/issues/18497
=> docs: Apply Markdown linting in Lifecycle Manager

Dockerfile, api/go.mod, go.mod
- bumps golang consistently between go config and docker image
- supersedes: https://github.com/kyma-project/lifecycle-manager/pull/1608
=> chore: Bump golang consistently to 1.22.4

config/grafana/status.json
Added the configuration for the Plutono dashboard under the `Kyma State Overview` to include the new view, which contains all the enabled modules and their respective active instances.
Resolves #1528
=> feat: Plutono configuration for displaying Enabled Modules in KCP

config/control-plane/kustomization.yaml, config/grafana/mandatory-modules.json
- adds the missing patch for the new mandatory-modules dashboard
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1468
=> chore: Add mandatory-modules dashboard grafana patch

api/v1beta2/kyma_types.go, config/crd/bases/operator.kyma-project.io_kymas.yaml, docs/technical-reference/api/kyma-cr.md
- adds the `.managed` flag to KymaCR `.spec.modules`
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1566
=> feat: Introduce `managed` flag to KymaCR `.spec.modules`

api/v1beta2/kyma_types.go, config/crd/bases/operator.kyma-project.io_kymas.yaml, docs/technical-reference/api/kyma-cr.md
This reverts commit b71285ff894f3407d15f493dcd01196beb3dbd3e.
- reverting the introduction of the field so that we can create a feature branch for the whole deletion mode feature
- reverting before branching of (and re-introeducing the field in the new branch) because otherwise we would get some troubles when rebasing the feature branch in the future to catch up in main
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1566
=> chore: Revert "feat: Introduce `managed` flag to KymaCR `.spec.modules` (#1652)"

api/v1beta2/kyma_types.go, config/crd/bases/operator.kyma-project.io_kymas.yaml, docs/technical-reference/api/kyma-cr.md
- re-introduce https://github.com/kyma-project/lifecycle-manager/pull/1652 which has been reverted https://github.com/kyma-project/lifecycle-manager/pull/1658 so that we can develop the whole feature in this feature branch
- resolves: https://github.com/kyma-project/lifecycle-manager/issues/1566
=> feat: Re-add `.spec.modules[].managed` to KymaCR

.github/actions/get-configuration/action.yaml, .github/workflows/test-e2e.yaml, .github/workflows/test-smoke.yml
- Bump k8s version to 1.29.6 for smoke and e2e test suites
- Introduce wait to img build on main builds for dispatch workflows
=> chore: Bump k8s version for e2e to 1.29.6

.golangci.yaml, cmd/main.go, docs/user-tutorials/01-10-control-plane-quick-start.md, internal/descriptor/provider/provider.go, internal/descriptor/provider/provider_test.go, pkg/testutils/kyma.go, pkg/testutils/moduletemplate.go, tests/integration/apiwebhook/moduletemplate_crd_validation_test.go, tests/integration/controller/eventfilters/suite_test.go, tests/integration/controller/kcp/remote_sync_test.go, tests/integration/controller/kcp/suite_test.go, tests/integration/controller/kyma/suite_test.go, tests/integration/controller/mandatorymodule/deletion/suite_test.go, tests/integration/controller/mandatorymodule/installation/suite_test.go, tests/integration/controller/withwatcher/suite_test.go, unit-test-coverage.yaml
remove DescriptorCache as input paremeter
=> chore: Refactor NewCachedDescriptorProvider

.golangci.yaml, cmd/main.go, docs/user-tutorials/01-10-control-plane-quick-start.md, internal/descriptor/provider/provider.go, internal/descriptor/provider/provider_test.go, pkg/testutils/kyma.go, pkg/testutils/moduletemplate.go, tests/integration/apiwebhook/moduletemplate_crd_validation_test.go, tests/integration/controller/eventfilters/suite_test.go, tests/integration/controller/kcp/remote_sync_test.go, tests/integration/controller/kcp/suite_test.go, tests/integration/controller/kyma/suite_test.go, tests/integration/controller/mandatorymodule/deletion/suite_test.go, tests/integration/controller/mandatorymodule/installation/suite_test.go, tests/integration/controller/withwatcher/suite_test.go, unit-test-coverage.yaml
* remove parameter for NewCachedDescriptorProvider
* fix dead link
* adjust unit test coverage
* fix flaky test
- ...
- ...
- ...
=> chore: Refactor NewCachedDescriptorProvider (#1695)

docs/developer-tutorials/local-test-setup.md
- Add versioning information
- Debug/Fix `yaml` examples provided in the guide
=> docs: Update KLM Local Test Setup Guide

api-version-compatibility-config.yaml, api/v1beta2/moduletemplate_types.go, config/crd/bases/operator.kyma-project.io_moduletemplates.yaml, docs/technical-reference/api/moduleTemplate-cr.md
Add deprecation notes to customStateCheck.
- Add
- deprecation note to customStateCheck in the api
- deprecation note to customStateCheck in the docs
fixes: #1616
=> chore: Add deprecation notes to customStateCheck

docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
- Fix User Docs with outdated command
=> docs: Fix User Docs with outdated commands

docs/technical-reference/controllers.md, docs/technical-reference/running-modes.md
- Update the technical reference documentation with typo fixes and grammar corrections
- Overall review of literature with changes in information presentation for better visibility
=> docs: Update technical reference documentation

cmd/main.go, config/manager/manager.yaml, config/watcher/certificate_setup.yaml, internal/pkg/flags/flags.go, internal/pkg/flags/flags_test.go, pkg/watcher/certificate_manager.go
- increases root cert key size to 4096
- increases client cert key size to 4096
- also makes this configurable by flag and prevent invalid / (currently) not supported values
- sets rotation policy to Always
- closes https://github.com/kyma-project/lifecycle-manager/issues/1771
=> chore: Increase cert key size to '4096'

.github/workflows/test-e2e.yaml
We often have one E2E test failing which cancels all other ongoing executions of E2E tests. Since our E2E tests are independent of each other, I would propose to not fail them fast. It would be good to know if only one test fails or multiple are affected by a change. And when re-running all tests, we have increased exposure to flakyness when re-running all tests.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#handling-failures
=> chore: Prevent E2E tests from failing fast

internal/declarative/v2/reconciler.go, internal/manifest/statecheck/state_check.go, internal/manifest/statecheck/state_check_test.go
- Updates the control flow in state check to return explicit errors on unexpected conditions, i.e., no manager found, fallthrough
- Updates the control flow in reconciler to exit early with state Deleting when manifest has a deletion timestamp
> The fallthrough case is not testable unfortunately. We may be able to get rid of it in the proposed further refactoring in the future.
- follow-up to https://github.com/kyma-project/lifecycle-manager/pull/1807
=> fix: Set manifest to deleting state; Raise errors on unexpected manager conditions

api/v1beta2/kyma_types.go, config/crd/bases/operator.kyma-project.io_kymas.yaml, tests/e2e/module_install_by_version_test.go, tests/integration/controller/kyma/kyma_module_enable_test.go, tests/integration/controller/kyma/kyma_module_version_test.go
Remove the `kyma.spec.modules[*].version` attribute from the API
When this is merged, if the user wants to enable the module using the specific version (see [here](https://github.com/kyma-project/lifecycle-manager/issues/1589)), the API server responds with: 
```
[...]: 
strict decoding error: unknown field "spec.modules[0].version"
```
Despite disabling the `version` attribute on the API level, the code for handling the attribute stays in the project so it's ready to be re-enabled anytime.
- Remove the `kyma.spec.modules[*].version` attribute from the k8s API
#1817
=> feat: Remove kyma.spec.modules[].version from api

internal/controller/kyma/setup.go
- `WithEventFilter` is setting global predicates applying to all `Watches.` In our case, this makes the specific predicates on the individual watches redundant.
- https://github.com/kyma-project/lifecycle-manager/pull/1792
- https://github.com/kyma-project/lifecycle-manager/pull/1854
=> fix: Remove redundant event filter predicates

config/grafana/status.json
A new panel in the Plutono dashboard under `Lifecycle Manager Kyma Status` to display the Modules which are in `Error` state.
Resolves #1745
=> feat: Add new Panel to display Modules in Error State

cmd/main.go, config/watcher/kustomization.yaml, internal/pkg/flags/flags.go, internal/pkg/flags/flags_test.go
Original PR https://github.com/kyma-project/lifecycle-manager/pull/1868 was merged to a feature branch so that we can run the E2E tests without the `pull_request_target` related issues. 
A test PR for running the E2E tests is here: https://github.com/kyma-project/lifecycle-manager/pull/1883
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1859
=> chore: Align runtime-watcher registry and make configurable (#1868)

api/shared/operator_labels.go, config/watcher/operator_v1beta2_watcher.yaml, internal/declarative/v2/default_transforms.go, internal/remote/skr_context.go, tests/integration/controller/kcp/helper_test.go
- changes `watched-by` label value from `lifecycle-manager` to `kyma`
See Test PR to feature branch with this change for test verification (still stuffering from the `pull_request_target` problem): https://github.com/kyma-project/lifecycle-manager/pull/1891
Resolves #1822
=> chore: Change `watched-by` label value from `lifecycle-manager` to `kyma`

config/grafana/watcher.json
- Check value of `kube_deployment_status_replicas_unavailable` and `kube_deployment_status_replicas_available` metrics in watcher components dashboard
=> fix: Filter kube_deployment_status_replicas_unavailable metric by value

docs/contributor/resources/01-kyma.md, docs/user/01-10-kyma-crd.md
- Adds documentation for the `managed` field in contributor docs
- References the whole Kyma contributor doc from Kyma user doc.
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1889
=> docs: Add docs for unmanaging modules

.github/workflows/lint-markdown-links.yml, api/README.md, docs/contributor/01-architecture.md, docs/contributor/02-controllers.md, docs/contributor/04-local-test-setup.md, docs/contributor/05-api-changelog.md, docs/contributor/resources/02-manifest.md, docs/contributor/resources/README.md, internal/controller/README.md, internal/manifest/README.md, tests/e2e/README.md
PR runs produced errors claiming that the action is not allowed `gaurav-nelson/github-action-markdown-link-check@v1 is not allowed to be used in kyma-project/lifecycle-manager. Actions in this workflow must be:`
- fixes the GH action to the allow-listed sha (corresponds to v1.0.15)
- using `@v1.0.15` directly also didn't work
- fixes all links that have broken in the meantime
=> chore: Use markdown-link-check@v1.0.15

internal/declarative/v2/default_transforms.go, internal/declarative/v2/default_transforms_test.go, internal/declarative/v2/options.go
- removes the `watched-by` label from the "rawManifest" resources. Label stays only on the KymaCR in the SKR
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1822
=> chore: Remove watched-by label from manifest resources

.github/workflows/build-image.yml, .github/workflows/create-release.yml, .github/workflows/test-e2e.yml
The PR verifying: https://github.com/kyma-project/lifecycle-manager/pull/1948
https://github.com/kyma-project/lifecycle-manager/issues/1943
=> chore: Decouple build image job from e2e

.golangci.yaml, cmd/main.go, config/rbac/namespace_bindings/watcher_certmanager_role.yaml, pkg/gatewaysecret/certmanagerclient.go, pkg/gatewaysecret/handler.go, pkg/gatewaysecret/handler_test.go, tests/e2e/rbac_privileges_test.go, unit-test-coverage.yaml
Fix for https://github.com/kyma-project/lifecycle-manager/pull/2004
=> fix: Handle Race Condition for Istio Gateway Secret

.github/actions/deploy-template-operator-with-modulereleasemeta/action.yml, .github/workflows/test-e2e-with-modulereleasemeta.yml, internal/controller/kyma/controller.go, pkg/module/sync/runner.go, pkg/util/error.go, scripts/tests/add_skr_host_to_coredns.sh, tests/e2e/Makefile, tests/e2e/skr_connection_lost_test.go
I decided to just set the state of all modules to "error" on SKR context initialization error, instead of reading the status of each module from the related `Manifest` CR.
I think it is correct action in all cases.
It would be incorrect if there's a permanent condition that prevents SKR context initialization (cluster deleted? wrong secret?) AND at the same time the manifest for a module would be NOT in an error state.
A simpler explanation: this approach would be incorrect if the Kyma reconciler cannot access SKR, but Manifest reconciler can (or it doesn't need to, but it sets a status different than "error")
Because such a situation is very unlikely, I decided to go with simpler solution to preserve resources (memory/cpu/network)
- …
=> fix: Modules should be in error state when SKR cluster is deleted

.run/Delete Test Clusters.run.xml, .run/Deploy KLM from registry.run.xml, .run/Deploy KLM from sources.run.xml, .run/Deploy kyma.run.xml, .run/E2E Tests.run.xml, .run/Install CRDs.run.xml, .run/Un-Deploy kyma.run.xml, .vscode/tasks.json, scripts/tests/README.md, scripts/tests/clusters_cleanup.sh, scripts/tests/create_test_clusters.sh, scripts/tests/deploy_klm_from_registry.sh, scripts/tests/deploy_klm_from_sources.sh, scripts/tests/deploy_kyma.sh, scripts/tests/e2e.sh, scripts/tests/install_crds.sh, scripts/tests/undeploy_kyma.sh, scripts/tests/version.sh
=> feat: Add Scripts to Automate Tasks in KLM

.vscode/tasks.json, api/v1beta2/modulereleasemeta_types.go, api/v1beta2/moduletemplate_types.go, cmd/main.go, config/crd/bases/operator.kyma-project.io_modulereleasemetas.yaml, internal/controller/kyma/controller.go, internal/remote/remote_catalog.go, internal/remote/remote_catalog_test.go, pkg/testutils/modulereleasemeta.go, pkg/testutils/moduletemplate.go, tests/e2e/modulereleasemeta_sync_test.go, tests/integration/controller/kcp/suite_test.go, tests/integration/controller/withwatcher/suite_test.go, unit-test-coverage.yaml
~~🚧 to be verified if we can also extend our integration tests~~ will be done as a separate PR
- introduces `beta` and `internal` flags to ModuleReleaseMeta
- respects the `beta` and `internal` flags when syncing ModuleReleaseMeta and its referenced modules to the SKR
- keeps the sync of ModuleTemplates using old format in it's current way
- can be removed once we migrated fully
- determination of what to sync fully covered in unit tests
- E2E test for syncing module release meta extended with the new cases
- resolves https://github.com/kyma-project/lifecycle-manager/issues/2059
=> feat: Support `internal` and `beta` flags in new module metadata

internal/controller/istiogatewaysecret/setup.go, unit-test-coverage.yaml
- Since predicate funcs default to returning true, they need to be explicitly overwritten with return false if we don't want to reconcile on `Delete` and `Generic` events.
=> chore: No reconcile on Delete and Generic events

cmd/main.go, config/watcher_local_test/kustomization.yaml, internal/pkg/flags/flags.go, internal/pkg/flags/flags_test.go
- added retryPeriod as explicit flag
- updated configuration for local test setup to use shortened leader election intervals
resolves #1836
=> fix: Configure short leader election intervals for local testing

pkg/testutils/kyma.go, tests/e2e/modulereleasemeta_sync_test.go
- Immediately requeue Kyma in `modulereleasemeta_sync` test to avoid timeouts
- As discussed in https://github.com/kyma-project/lifecycle-manager/issues/2127, we rely on regular requeue intervals in production
- https://github.com/kyma-project/lifecycle-manager/issues/2127
=> chore: Add immediate requeues to MRM sync test

.vscode/launch.json
- adds launch configs for integration and e2e tests from VSCode
=> chore: Add VSCode launch config for tests

api/v1beta2/moduletemplate_types.go, api/v1beta2/moduletemplate_types_test.go, internal/descriptor/cache/key.go, internal/maintenancewindows/maintenance_window.go
- Adds another set of helpers to the ModuleTemplate type for getting version and name
- Background: make it more robust when handling different gerneations of ModuleTempalte (old ones, new ones)
- e.g., in the maintenance window logic
- https://github.com/kyma-project/lifecycle-manager/issues/2101
=> chore: Add version and name helpers to ModuleTemplate

internal/declarative/v2/reconciler.go, internal/manifest/finalizer/handler.go, internal/manifest/labelsremoval/labels_removal.go, internal/manifest/labelsremoval/labels_removal_test.go, internal/manifest/modulecr/client.go, pkg/testutils/builder/manifest.go, tests/e2e/module_unmanage_test.go, unit-test-coverage.yaml
- fixes the nil pointer exception
- refactors the label removal service
- it should be e2e responsible for label removal from all objects
- therefore, the check if needed for defaultCR and respective lookup moved from reconciler into the service
- this way the removal can now be completely unit tested
- extends the unmanaging e2e test to include the case wehere CustomResourcePolicy is Ignore
- closes #2225
=> fix: Nil pointer when unmanaging module with `Ignore` CustomResourcePolicy

internal/manifest/skrresources/collector.go, internal/manifest/skrresources/collector_test.go, internal/manifest/skrresources/manifestcollector.go, internal/manifest/skrresources/ssa.go, internal/manifest/skrresources/ssa_test.go, internal/manifest/skrresources/sync.go
The idea behind this PR is as follows:
In order to create a robust "unknown managers cleanup" process, we first must collect the data.
This PR allows to collect this data in the logging stream for easy analysis.
Once it starts working, we'll be able to see what kind of "unknown managers" are there in the environments. Then we can add logic to fix these "unknown" managers. During that process, the amount of logs for "unknown managers" should decrease.
After a few iterations we should achieve the state where (almost) no logs for "unknown" managers are produced.
At that time we should make the code introduced here more "production-ready", for example, replace env vars with proper flags etc.
For now it's a bit ad-hoc because it's not clear yet which parts of it will remain in …
=> feat: Unexepected field managers reporting

.run/Launch KLM locally.run.xml, config/watcher/kustomization.yaml
- Bump the reference to used default watcher image to 1.1.14
=> chore: Bump watcher reference to latest release

api/shared/operator_labels.go, internal/remote/skr_context.go, internal/remote/skr_context_test.go, maintenancewindows/resolver/resolver.go, tests/e2e/labelling_test.go
- Propagate the label `kyma-project.io/global-account-id` from KCP to SKR
- Propagate the label `kyma-project.io/subaccount-id` from KCP to SKR
Resolves: #2235
=> feat: Propagate Global Account and SubAccount Labels

api/v1beta2/watcher_types.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/operator.kyma-project.io_watchers.yaml
- Makes watcherCR `spec.labelsToWatch` optional
Resolves #2341
=> chore: Make WatcherCR `spec.labelsToWatch` optional

pkg/module/common/module.go, pkg/module/common/module_test.go, pkg/testutils/manifest.go, tests/e2e/mandatory_module_test.go, tests/e2e/manifest_reconciliation_test.go
- Populate Manifest operator.kyma-project.io/channel label for non-mandatory modules
- Adjust unit and E2E tests
Resolves #2556
=> fix: Populate Manifest operator.kyma-project.io/channel label for non-mandatory modules

internal/declarative/v2/reconciler.go
Evicts client cache and records requeue reason for all
connection-related errors, regardless of deletion timestamp.
- Evict cache should not limited to deleted Manifest, because skr secret also rotated, so the normal manifest connection error should trigger cache evicting as well 
=> fix: Removes deletion timestamp check from error handling

tests/e2e/skr_secret_rotation_test.go, tests/e2e/utils_test.go
The `CheckPodLogs` is not reliable. If the test runs for a longer time, the expected log message can't be fetched, changed to a more stable check to verify skr-webhook readiness by `DeploymentIsReady`
=> chore: Replace flaky `CheckPodLogs` with `DeploymentIsReady` for detect SKR watcher deployment

api/go.mod, api/go.sum, go.mod, go.sum, internal/remote/modulereleasemeta_syncer_test.go, internal/remote/moduletemplate_syncer_test.go, internal/service/skrclient/client_proxy.go
- bumps controller-runtime to `0.22.2`
- I made a mistake and earlier ignored the whole `0.22` minor https://github.com/kyma-project/lifecycle-manager/pull/2705#issuecomment-3247951247
- with `0.22.0` the new `client.Client.Apply` was introduced and `client.Apply` was deprecated. The deprecation of `client.Apply` was reverted in `0.22.1` as the support for `client.Client.Apply` was incomplete (missing sub-resource writer). Once the full support for `client.Client.Apply` is there and the actual deprecation of `client.Apply` happens, we must make code changes as described in this ticket https://github.com/kyma-project/lifecycle-manager/issues/2707
- we still have the problem with our `ClientProxy`
- as of now, we expect it to implement …
=> chore: Bump controller-runtime to 0.22.2
