kyma-project/lifecycle-manager

operator/Dockerfile
operator/config/samples/component-integration-installed/rbac/component_rbac.yaml
operator/pkg/util/kyma_util.go

- add missing package for dockerfile
- fix ServiceAccount naming, missing prefix
- change manifest naming

Fix component naming and some other bugs

---

operator/config/manager/manager.yaml
operator/config/samples/secret/k3d-secret-gen.sh
operator/controllers/kyma_controller_test.go

- skip unit tests
- increase resource limits for kyma-operator

Improve secret generate script

---

operator/PROJECT
operator/api/v1alpha1/moduletemplate_webhook.go
operator/api/v1alpha1/webhook_suite_test.go
operator/config/certmanager/certificate.yaml
operator/config/certmanager/kustomization.yaml
operator/config/certmanager/kustomizeconfig.yaml
operator/config/default/manager_webhook_patch.yaml
operator/config/default/webhookcainjection_patch.yaml
operator/config/webhook/kustomization.yaml
operator/config/webhook/kustomizeconfig.yaml
operator/config/webhook/manifests.yaml
operator/config/webhook/service.yaml
operator/main.go

this sets up the validating webhook for moduletemplates to validate the OCM Component Descriptor

feat: setup validating webhook for moduletemplate

---

operator/Makefile

Part of https://github.com/kyma-project/test-infra/issues/5859
Necessary for https://github.com/kyma-project/test-infra/pull/5866

Adapt Makefile for Image build

---

operator/controllers/kyma_controller.go
operator/pkg/module/sync/runner_impl.go

- put more thing into module/sync

Refactor controller logic

---

operator/config/default/kustomization.yaml

One liner to fix main deployment. In future this would have been covered by smoke tests

fix: disable grafana by default

---

operator/config/rbac/role.yaml
operator/controllers/kyma_controller.go
operator/controllers/kyma_controller_helper_test.go
operator/controllers/kyma_controller_remote_sync_test.go
operator/controllers/kyma_controller_test.go
operator/controllers/kyma_moduleinfo_test.go
operator/controllers/module_catalog_controller.go
operator/controllers/moduletemplate_test.go
operator/pkg/module/sync/runner_impl.go

- Refactoring existing test
- Add module template test

Fix moduletemplate changes not propagated to manifest CR

---

operator/Makefile
operator/config/default/kustomization.yaml
operator/config/load_test/kustomization.yaml

- add load-test-deploy make command

Refactor load_test as dedicate kustomize build instead of component

---

operator/config/istio/gateway.yaml
operator/config/load_test/kustomization.yaml
operator/config/load_test/patches/gateway_namespace_replace.yaml
operator/controllers/setup.go
operator/go.mod
operator/internal/custom/istio_client.go
operator/main.go
operator/pkg/dynamic/informers.go

- add patch for gateway namespace
- remove VirtualService
- watches manifest instead of all resources under operator group

Dynamic Informers watches manifest instead of all resources

---

samples/template-operator/README.md

- Added default resolver to sample implementation -> otherwise this sample implementation would not work
- Removed input Parameter from `defaultResolver()` since there should not be one
- Fixed one typo

Fixed some small stuff

---

operator/controllers/kyma_controller.go
operator/controllers/watcher_controller.go
operator/main.go
operator/pkg/watch/template_change.go

Implement based on kyma community concept - Consistent Logging
https://github.com/kyma-project/community/tree/main/concepts/observability-consistent-logging

Reconfig logger format to follow kyma community concept

---

controllers/kyma_controller.go
pkg/catalog/remote_catalog.go
pkg/deploy/chart_manager.go
pkg/remote/context.go
pkg/remote/kyma_synchronization_context.go

fix: make remote sync more resilient to missing resources and CRDs

---

pkg/catalog/remote_catalog.go

Applies Catalog Data concurrently to allow for faster synchronisation of ModuleTemplates

chore: concurrent Server Side Apply for catalog sync

---

pkg/catalog/remote_catalog.go

This fixes accidental deletes from the diff computation that is caused by SKR items not being present before the SSA and thus being deleted right after as potential diff.
This is a leftover regression as previously we used client side apply and the old diff logic was still in place to calculate deletes. However the delete calculation happened BEFORE the apply, so they were deleted right after

fix: catalog accidental delete of runtime templates due to legacy diff calculation

---

pkg/img/parse.go

This PR adds support for fetching modules pushed to OCI Registries using [Component Name Mapping sha256-digest](https://gardener.github.io/component-spec/component_descriptor_registries.html#component-name-mapping-sha256-digest).
This fixes: #364 
I tested it both with local k3d registry and public Dockerhub (registry-1.docker.io).
**Related Issues**
Fixes: #364

Add support for sha256-digest name mapping

---

Makefile
api/v1alpha1/kyma_types.go
api/v1alpha1/operator_labels.go
api/v1alpha1/webhook_crd_test.go
controllers/kyma_controller.go
controllers/kyma_controller_helper_test.go
controllers/kyma_controller_test.go
controllers/moduletemplate_test.go
controllers/suite_test.go
controllers/withwatcher/kyma_controller_test.go
controllers/withwatcher/suite_with_watcher_test.go
controllers/withwatcher/watcher_controller_test.go
pkg/security/san_pinning_test.go
tests/smoke_test/smoke_test.go

add skip reconciliation label
add test
Issue related: https://github.com/kyma-project/lifecycle-manager/issues/315

Provide a way to stop reconciliation for kyma clusters

---

api/v1beta1/kyma_types.go
api/v1beta1/manenv_annotations.go
api/v1beta1/manenv_labels.go
controllers/kyma_controller.go
main.go
pkg/metrics/metrics.go
pkg/status/kyma_helper.go
pkg/watcher/certificate.go

Introduce custome metrics for tracking Kyma status.
See: https://github.com/kyma-project/lifecycle-manager/issues/380

Introduce custom Kyma metrics

---

.github/workflows/test.yml
tests/smoke_test/smoke_test.go

This heavily simplifies the smoke tests and adds a `control-plane` variety which also uses Istio and the service monitor CRD so that we can integrate into a managed simulated offering

Istio smoke test setup

---

Makefile

Makefile: Divide CRD Installation in Deploy Target

---

docs/developer/reference-documentation.md

Description:
* Broken link after declarative pkg moved to internal

Fix reference docu link

---

docs/user/quick-start.md

related issue:
https://github.com/kyma-project/lifecycle-manager/issues/425

mention interactive tutorial in quick start

---

api/v1beta1/moduletemplate_webhook.go
api/v1beta1/moduletemplate_webhook_test.go
controllers/suite_test.go

related issue https://github.com/kyma-project/lifecycle-manager/issues/459

validateVersion only compare major minor patch

---

config/control-plane/kustomization.yaml
config/control-plane/patches/dashboard_cm_patch.yaml
config/control-plane/patches/metrics_namespace_replace.yaml

Description:
* Add grafana label to dashboard CMs
* Rename patch

Enable Grafana dashboards for control-plane target

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation-improvement.md
.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/security-vulnerability.md
.github/pull-request-template.md

**Description** 
Changes made in the pull request:
- Added pull requests and issues templates
Related issue
#497

Add issues and PR templates

---

Makefile
config/control-plane/kustomization.yaml
config/grafana/kustomization.yaml
config/grafana/status.json
controllers/kyma_controller.go
pkg/metrics/metrics.go

- Fix state label for status metric
- Add initial dashboard for status visualization
- Add module state metric
* https://github.com/kyma-project/lifecycle-manager/issues/380

Fix metric label & add status dashboard

---

controllers/kyma_controller_test.go
pkg/status/conditions.go
pkg/status/conditions_test.go

kyma_controller: Add Kyma CR Conditions Whitelist

---

.github/workflows/test.yml
config/samples/component-integration-installed/operator_v1beta1_moduletemplate_kcp-module.yaml

To gain a bit more confidence for the lifecycle manager, in current smoke test, enable template operator, and check kyma readiness.

deploy template operator in smoke test

---

.github/workflows/test.yml
config/control-plane/kustomization.yaml
config/manager/kustomization.yaml
docs/developer/local-test-setup.md
skr-webhook/resources.yaml

- Update registry references from `eu.gcr.io/kyma-project` to `europe-docker.pkg.dev/kyma-project/prod`
* https://github.com/kyma-project/lifecycle-manager/issues/523

Update registry references

---

config/watcher_local_test/kustomization.yaml

Change v1beta to v1beta2 Watcher kustomize

---

api/v1beta1/kyma_conversion.go

Change conversion webhook

---

config/grafana/overview.json

- Fix label matcher for Reconcile Duration panel

Fix overview dashboard panel

---

main.go

add rate limiter to manifest

---

main.go

- Add more info logs to removing storedVersions

Add more info logs for removing storedVersions

---

config/rbac/role.yaml
controllers/kyma_controller.go
main.go

- Add RBAC access to update CRD status

Add RBAC access to update CRD status

---

api/v1beta2/kyma_types.go
api/v1beta2/webhook_kyma_crd_validation_test.go
config/crd/bases/operator.kyma-project.io_kymas.yaml

- Add a validation to have unique modules based on their name
Resolves #610

Validate unique modules in kyma spec

---

config/control-plane/kustomization.yaml

Increase kyma worker

---

controllers/control-plane/kcp_controller_helper_test.go
controllers/control-plane/kcp_controller_remote_sync_test.go

- Added an integration test for the Kyma and ModuleTemplate CRDs update to SKR cluster as well as the CRDs annotations in KCP Kyma CRD being updated

Integration test for CRDs Annotations Update in KCP Kyma CR

---

pkg/channel/lookup.go

This PR elaborate channel skew message by providing more details

Improve channel skew message

---

internal/declarative/v2/reconciler.go

- Fix failing module from status after being deleted from spec.modules
Resolves #629

Remove failing module from status after being deleted from spec.modules

---

controllers/control-plane/kcp_controller_helper_test.go
controllers/control-plane/kcp_controller_remote_sync_test.go
controllers/control-plane/kcp_suite_test.go

- Have a runtime cluster for each test
Resolves #658

Fix flaky tests

---

controllers/control-plane/kcp_controller_helper_test.go
controllers/control-plane/kcp_controller_remote_sync_test.go
controllers/control-plane/kcp_controller_test.go
controllers/control-plane/kcp_manifest_test.go
controllers/control-plane/kcp_suite_test.go

- Provision remote cluster envtest for each test
Resolves #658

Provision remote cluster envtest for each test

---

controllers/control-plane/kcp_controller_helper_test.go
controllers/control-plane/kcp_controller_remote_sync_test.go
controllers/kyma_controller.go
controllers/moduletemplate_test.go
pkg/remote/kyma_synchronization_context.go

- Remove copying old remote Kyma CRs
* https://github.com/kyma-project/lifecycle-manager/pull/625
* https://github.com/kyma-project/lifecycle-manager/issues/599

Remove renaming old remote kymas

---

api/v1beta2/moduletemplate_types.go

- Add resourceVersion to ModuleTemplate cache key to fetch the descriptor if any changes were made to the module template.
Fixes #652

Add resourceVersion to moduletemplate cache Key

---

api/scheme.go

api/scheme.go: Remove Unnecessary Conversion Functions

---

controllers/manifest_controller.go
internal/declarative/v2/options.go
internal/declarative/v2/reconciler.go
internal/declarative/v2/reconciler_test.go
internal/declarative/v2/test/v1/declarative_test.go
internal/manifest/v1beta1/custom_resource.go
internal/manifest/v1beta1/suite_test.go

- Prevent deletion of the CRD before CR
Fixes #668 
#663

Remove CRD after other resources

---

controllers/control-plane/kcp_controller_remote_sync_test.go
pkg/remote/crd_upgrade.go
pkg/remote/kyma_synchronization_context.go
pkg/remote/remote_catalog.go

- Recreate deleted Kyma and ModuleTemplate CRDs in SKR after their deletion
Fixes #609

Recreate Kyma and ModuleTemplate CRDs in SKR after their deletion

---

flags.go

- Increase client qps and burst
Resolves #645

Increase client qps and burst

---

docs/technical-reference/api/README.md
docs/technical-reference/api/kyma-cr.md
docs/technical-reference/api/manifest-cr.md
docs/technical-reference/architecture.md
docs/technical-reference/running-modes.md

- Added linking
- Language /structure fixes

Review and update the technical reference documentation in the Lifecycle Manager repo

---

controllers/control-plane/kcp_controller_helper_test.go
controllers/kyma_controller.go
controllers/moduletemplate_test.go
internal/declarative/v2/reconciler.go
internal/declarative/v2/test/v1/declarative_test.go
internal/declarative/v2/test/v1/helper_test.go
main.go
pkg/remote/crd_upgrade.go

- If certain conditions are met we can set the ready condition to false, which was unused until now

set sync steps ready conditions to false

---

docs/developer-tutorials/config-private-registry.md

- Updated the config-priv-reg tutorial

Update config-priv-reg tutorial

---

.github/workflows/test.yml
config/control-plane/kustomization.yaml

- Remove patches for success intervals, we will add them to the management-plane-config
- Remove gke specific node annotation
* https://github.com/kyma-project/lifecycle-manager/issues/704

Remove control-plane patches to be moved to management-plane-config

---

config/control-plane/kustomization.yaml
config/default/kustomization.yaml
flags.go

- remove control plane max worker patch
- setup default max worker higher in order to compatible with landscape release (will revert it back after add overwrite in management plane config)

Remove control plane max worker patch

---

docs/README.md
docs/developer-tutorials/config-private-registry.md
docs/developer-tutorials/local-test-setup.md
docs/developer-tutorials/prepare-gcr-registry.md
docs/developer-tutorials/provision-cluster-and-registry.md
docs/developer-tutorials/starting-operator-with-webhooks.md

- Updated the developer tutorials

Update developer tutorials

---

flags.go
pkg/img/parse.go

Fix installation of a Module generated using `sha256` OCM Name Mapping

---

controllers/control-plane/kcp_controller_helper_test.go
controllers/control-plane/kyma_remote_sync_test.go
flags.go

- Add a test for SKR Kyma recreation if it gets deleted
- Fix the listing issue (gomnd) for a magic number in flag.go

Testing SKR Kyma recreation when it gets deleted

---

controllers/control-plane/kyma_remote_sync_test.go
controllers/kyma_controller_helper_test.go
controllers/kyma_module_channel_test.go
controllers/kyma_test.go

Add missing kyma tests

---

config/watcher/operator_v1beta2_watcher.yaml

Since we currently want to focus on the KymaWatch mechanism, we decided to disable the Manifest Watcher for the current time.
In future it may will be enabled again.

Disable Manifest Watcher

---

.golangci.yaml

- Set linter timeout to 15min
- Remove concurrency and use default no of cores

linter fix: increase timeout and remove concurrency

---

config/default/kustomization.yaml
controllers/control-plane/kcp_controller_test.go
controllers/control-plane/kcp_manifest_test.go
controllers/kyma_moduleinfo_test.go
controllers/manifest_test.go
flags.go
tests/smoke_test/module_upgrade/moduletemplate_template_operator_fast.yaml

- Set default max worker to 1
- Remove default profile overwrites
- Fix smoke test by introducing updated module template

set default max worker to 1 and fix smoke test

---

.github/workflows/pull-lifecycle-mgr-lint.yml
.golangci.yaml
Makefile
controllers/control-plane/kcp_manifest_test.go
controllers/kyma_controller.go
controllers/kyma_controller/kyma_module_channel_test.go
controllers/kyma_controller/manifest_test.go
internal/declarative/v2/object.go
internal/declarative/v2/reconciler.go
internal/manifest/ready_check.go
pkg/testutils/utils.go
tests/e2e_test/watcher_test.go

- Add pull-lifecycle-mgr-lint workflow
- Pin version to 1.53.3
- Disabled `depguard` that comes with the version bump, we have no package whitelist
- Increase max cyclop a bit to 20 (recommended for go is 30)
- Add timeout: 15m
- Remove autofix for issues, this swallows issues on PRs
- Fix new issues appearing since version bump and autofix removal

Add Github Actions lint workflow

---

config/control-plane/kustomization.yaml

- Remove purge reconciler configs from control-plane Kustomization
#746

Remove purge finalizer configs from control-plane

---

controllers/kyma_controller.go
internal/manifest/parse.go
pkg/channel/lookup.go
pkg/module/parse/template_to_module.go
pkg/remote/context.go
pkg/remote/kyma_synchronization_context.go
pkg/remote/remote_catalog.go
pkg/watcher/skr_webhook_manifest_manager.go

This PR fix ignored error and improper panic which complained by checkmarx

Fix ignored error and improper panic

---

api/v1beta2/moduletemplate_types.go
controllers/kyma_controller/moduletemplate_test.go
pkg/module/parse/template_to_module.go

Remove Config Layer Code for Manifest

---

api/v1beta2/operator_annotations.go
api/v1beta2/webhook_moduletemplate_crd_validation_test.go
controllers/control-plane/kcp_controller_helper_test.go
controllers/control-plane/kyma_remote_sync_test.go
controllers/kyma_controller/kyma_controller_helper_test.go
controllers/kyma_controller/kyma_module_channel_test.go
controllers/kyma_controller/kyma_test.go
controllers/kyma_controller/moduletemplate_install_test.go
controllers/kyma_controller/moduletemplate_test.go
pkg/module/sync/runner_impl.go
pkg/testutils/utils.go

- Provide empty resource namespace for cluster scoped modules
#741

Provide empty resource namespace for cluster scoped modules

---

internal/declarative/v2/util.go
tests/e2e_test/kyma_deletion_test.go

- error refactoring introduced a bug

Fix: nil error during rest mapping

---

pkg/module/parse/template_to_module.go

revert remove config layer

---

controllers/kyma_controller.go

- Remove all finalizers when Kyma is under deletion and no secret found
Resolves #816

Remove all Kyma finalizers when Kyma is under deletion and no secret found

---

docs/technical-reference/api/moduleTemplate-cr.md
docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md

related issue: https://github.com/kyma-project/lifecycle-manager/issues/196

add customStateCheck into api doc

---

config/grafana/overview.json

config/grafana: Add Listener Metrics

---

.github/workflows/lint-conventional-prs.yml

Adds a PR title linter as a GitHub action to impose conformance to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
**PR title scheme**
Every PR MUST adhere to the following scheme:
`type`(`scope`?): `subject`
Examples:
feat(config): Add Listener Metrics 
fix: Add a warning state propagation
feat: Introduce a new error ErrAccessSecretNotFound 
chore: bump LM deps
chore: Remove watcher cm config
test(e2e): Add a Kyma deletion smoke test
The list of suggested PR types:
- **deps**. The changes in the external dependencies.
- **chore**. Anything not covered by the above categories (e.g., refactoring or artefacts building alternations).
- **docs**. Changes regarding the documentation.
- **feat**. A new feature or functionality change.
- **fix**. A bug …

chore: Add a Conventional Commits linter as a GitHub action

---

api/v1beta2/moduletemplate_types.go

Related to [CLI 1729](https://github.com/kyma-project/cli/issues/1729)

fix: Add YAML Struct Tags to CustomStateCheck

---

.github/workflows/e2e-test.yml
controllers/control-plane/kcp_controller_helper_test.go
controllers/control-plane/kyma_remote_sync_test.go
controllers/kyma_controller.go
docs/developer-tutorials/local-test-setup.md
pkg/remote/kyma_synchronization_context.go
pkg/remote/kyma_synchronization_context_test.go
pkg/testutils/utils.go
tests/e2e_test/status_propagation_test.go

- Implements https://github.com/kyma-project/lifecycle-manager/issues/756

chore: Use SKR Module List as single source of Truth

---

pkg/watcher/skr_webhook_manifest_manager.go

Those log message in this PR not brings too much value as info log, instead flooding the log message of LM.

chore: Make info level log to debug

---

controllers/setup.go

- Add event filter to avoid reconciliations when Kyma status subresource gets updated
#853

fix: Avoid purge reconciliation on status sub resource update

---

.github/ISSUE_TEMPLATE/feature-request.yml

Augments the feature request GitHub Issue Template with a [form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).

chore(github, sdlc): Replace the feature request issue template with a form

---

internal/controller/purge/metrics/metrics.go

- purge error metric was initialized with 3 labels but updated with 4, this fixes that

fix: Purge error metric

---

config/grafana/overview.json

- Add to LM overview grafana dashboard an new panel:
- avg purge duration
- purge total
- error with details
* https://github.com/kyma-project/lifecycle-manager/issues/734

feat: Add panel for purge metrics & cleanup other panels

---

tests/e2e_test/watcher_test.go

- Add validation for status subresource watching
Resolves https://github.com/kyma-project/runtime-watcher/issues/63

test: Runtime watcher test for status subresource watching

---

internal/controller/event-filters/eventfilter_test.go
internal/controller/event-filters/helper_test.go
internal/controller/event-filters/suite_test.go

- Added a test to verify that Kyma gets reconciled immediately when a label is added (to test the `LabelChangedPredicate`)
- Added a test to verify that Kyma gets reconciled immediately when the spec is changed (for the `GenerationChangedPredicate`)
Resolves #935

test: Add integration test for testing the event filters behavior

---

go.mod
go.sum

put istio related dep in one import block to indicate they should update all at once.

chore: Put istio related dep in one import block

---

.github/workflows/report-acceptance-criteria.yml
tests/e2e_test/Makefile

Adds an ad hoc report that outlines the acceptance criteria from the E2E test suite.
#925

chore(sdlc, reporting): Adds a GitHub action to generate an ad hoc acceptance criteria report

---

.github/workflows/report-acceptance-criteria.yml

Fixes the indentation in the GH Action config file.

chore: Fix the indentation in the config file

---

api/v1beta2/moduletemplate_types.go
api/v1beta2/moduletemplate_types_test.go

- Add validation for module version before using it as part of ComponentDescriptorCache Key
- Add a unit test case
Resolves #929

chore: Add validation for module version before using it as part of ComponentDescriptorCache Key

---

internal/controller/common/metrics/metrics.go
internal/controller/kyma_controller.go
pkg/status/kyma_helper.go

- Emit a warning event if the required metrics label or annotation are missing
Resolves #699

chore: Emit a warning event if metrics annotation or label are missing

---

.github/workflows/lint-golangci.yml
.github/workflows/test-e2e.yml
.github/workflows/test-smoke.yml
.github/workflows/test-unit.yml
config/crd/bases/operator.kyma-project.io_manifests.yaml
config/crd/bases/test.declarative.kyma-project.io_testapis.yaml
docs/technical-reference/api/manifest-cr.md

- Add documentation for the Manifest `operator.kyma-project.io/skip-reconciliation` label
- Removed paths section from the GitHub Actions sine they are now required for the PR to get merged so they should run in every PR
Resolves #973

docs: Add Manifest skip label documentation

---

api/v1beta2/moduletemplate_types.go
api/v1beta2/moduletemplate_types_test.go

- Use `github.com/Masterminds/semver/v3` package
Resolves #1009

chore: Use the correct semver package

---

cmd/flags.go
cmd/main.go
config/crd/bases/operator.kyma-project.io_manifests.yaml
config/crd/bases/test.declarative.kyma-project.io_testapis.yaml

- Do not start Lifecycle Manager if no watcher image is specified
- Remove the hardcoded watcher image value in flags
Resolves #983

Do not start Lifecycle Manager if no watcher image is specified

---

.golangci.yaml

- Enable godox linter
Resolves #1004

chore: Enable godox linter

---

config/grafana/overview.json

The Visualization should be graph instead of state

fix: Purge metrics

---

config/control-plane/kustomization.yaml
config/watcher/kustomization.yaml
config/watcher_local_test/kustomization.yaml

fix(kustomize): Remove useless patches, introduce missing transformer

---

config/rbac/role.yaml
internal/controller/kyma_controller.go

add watch permission to certificates

fix: Add missing watch permission for certificates

---

LICENCE

Add LICENCE File to resolve #1030
- Add LICENCE File
#1030

chore: Add LICENCE file

---

api/v1beta2/moduletemplate_types.go
config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
docs/technical-reference/api/manifest-cr.md
docs/technical-reference/api/moduleTemplate-cr.md

- Add `mandatory` optional boolean field to the ModuleTemplate spec
- Update API documentation for the ModuleTemplate to add the mandatory field documentation
Resolves #1050

feat(Mandatory Modules): Add Mandatory optional field to the ModuleTemplate Spec

---

config/grafana/overview.json

replace [rate](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) with [increase](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) to have better understanding for certain metrics.

refactor: Change rate to increase

---

.github/workflows/lint-markdown-links.yml
docs/README.md
docs/technical-reference/api/kyma-cr.md
docs/technical-reference/architecture.md
docs/technical-reference/controllers.md
docs/user-tutorials/01-10-control-plane-quick-start.md
internal/declarative/README.md

- Fix markdown lint check configs
- Fix not working links
Resolves #1019

fix: Fix markdown lint check 

---

cmd/main.go
internal/controller/kyma_controller.go
internal/controller/purge_controller.go
internal/pkg/metrics/common.go
internal/pkg/metrics/kyma_metrics.go
internal/pkg/metrics/purge_metrics.go
pkg/module/sync/runner_impl.go

refactoring metrics related code into internal package.

refactor: Move metrics to internal package

---

config/grafana/overview.json

- some diagram use `increase` is misleading, revert back to `rate`
- updated fixed interval to dynamic `$__rate_interval`

fix: Update metrics function

---

cmd/flags.go
cmd/main.go
pkg/queue/requeue_intervals.go
tests/integration/controller/controlplane/kcp_suite_test.go
tests/integration/controller/eventfilters/suite_test.go
tests/integration/controller/kyma/suite_test.go
tests/integration/controller/withwatcher/suite_with_watcher_test.go

- Increase Timeout for Warning State to 30 seconds
- Have a flag to configure it

feat: Configurable Requeue Interval for Warning State

---

.github/workflows/test-e2e.yml
tests/e2e_test/Makefile
tests/e2e_test/ca_certificate_rotation_test.go
tests/e2e_test/kyma_deletion_test.go
tests/e2e_test/kyma_metrics_test.go
tests/e2e_test/module_deletion_test.go
tests/e2e_test/module_upgrade_test.go
tests/e2e_test/no_default_cr_test.go
tests/e2e_test/purge_controller_test.go
tests/e2e_test/purge_metrics_test.go
tests/e2e_test/warning_status_propagation_test.go
tests/e2e_test/watcher_test.go

- Using the E2E test Glossary
- Following the Given, When, Then convention in writing the test cases
Resolves #938

chore: Refactoring E2E test suite to align with the Glossary and the GWT naming

---

.github/DISCUSSION_TEMPLATE/q-a.yml

- Introduce the form for the Q&A discussion category

chore: GH form for Q&A discussion category

---

pkg/watcher/certificate.go
pkg/watcher/certificate_cache.go
pkg/watcher/skr_webhook_manifest_manager.go

- Save the CA Certificate by value not as a pointer in cache
- Retrieve status from cache

chore: Save CA Certificate value instead of pointer in cache

---

.github/DISCUSSION_TEMPLATE/q-a.yml

chore: Update the discussion template bool values

---

config/watcher/kustomization.yaml

- Use the latest release 0.0.2 for watcher to deploy on skr runtimes

deps: Bump watcher image version to 0.0.2 release

---

internal/pkg/metrics/common.go

chore: Adds an external dependency

---

internal/pkg/metrics/common.go

- Reverts the unnecessary dependency used to test the package report

chore: Reverts the unnecessary dependency used to test the package report

---

cmd/flags.go
cmd/main.go

- Add `dropStoredVersion` flag
- Rename `dropVersionFromStoredVersions` to `dropStoredVersion`
- If the flag is empty, the function doesn't get called

feat: Add dropStoredVersion flag

---

cmd/main.go

- Checkmarx detected a candidate for race condition here
- Pass the to be dropped version as argument to the goroutine

fix: Pass drop version as arg to eliminate race condition

---

api/shared/operator_labels.go
api/v1beta1/kyma_conversion.go
api/v1beta2/kyma_types.go
api/v1beta2/moduletemplate_types.go
internal/manifest/spec_resolver.go
pkg/module/sync/runner.go
pkg/status/conditions_test.go
pkg/testutils/kyma.go
tests/integration/controller/controlplane/kcp_controller_test.go
tests/integration/controller/controlplane/kcp_manifest_test.go
tests/integration/controller/controlplane/kyma_remote_sync_test.go
tests/integration/controller/kyma/kyma_test.go
tests/integration/controller/kyma/moduletemplate_install_test.go

- Move `EnableLabelValue` and `DisableLabelValue` to `shared`

feat: Move EnableLabelValue and DisableLabelValue

---

api/v1beta1/kyma_types.go
api/v1beta1/manifest_types.go
api/v1beta1/moduletemplate_types.go
api/v1beta1/watcher_types.go
api/v1beta2/kyma_types.go
api/v1beta2/manifest_types.go
api/v1beta2/moduletemplate_types.go
api/v1beta2/watcher_types.go
config/crd/bases/operator.kyma-project.io_kymas.yaml
config/crd/bases/operator.kyma-project.io_manifests.yaml
config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
config/crd/bases/operator.kyma-project.io_watchers.yaml

- Set v1beta2 as storage version instead of v1beta1
#1118

chore: Set v1beta2 as storage version

---

config/grafana/overview.json

- Add new panels and row "SKR-Webhook" to overview dashboard for watcher_* runtime metrics
* https://github.com/kyma-project/runtime-watcher/issues/146

feat: Add panels for new skr-webhook metrics

---

internal/controller/kyma_controller.go
internal/pkg/metrics/kyma.go
pkg/testutils/metrics.go
tests/e2e/kyma_metrics_test.go

- Add metrics with label for the requeue of Kyma reconciliation
#1112

feat: Kyma requeue reason metrics

---

config/grafana/overview.json

- Add kyma requeue reasons metrics to panel
Resolves #1112

feat: Add kyma requeue reasons metrics to panel

---

internal/pkg/metrics/metrics_test.go
internal/pkg/metrics/purge.go

- Add unit test for checking default metrics names are not changed.
Closes #1109

feat(metrics_test.go): Add Metrics Name Unit Test

---

config/watcher/kustomization.yaml

- use latest version of watcher since fix and introducing metrics
* https://github.com/kyma-project/runtime-watcher/issues/176

deps: Bump watcher image to latest build

---

docs/technical-reference/controllers.md

- Add documentation for Mandatory modules
Resolves https://github.com/kyma-project/lifecycle-manager/issues/1053

docs: Mandatory module controller documentation

---

config/grafana/kustomization.yaml

fix: Create CM for watcher dashboard

---

Dockerfile
Makefile
cmd/main.go
internal/controller/kyma_controller.go
internal/pkg/flags/flags.go
internal/pkg/flags/flags_test.go
tests/integration/controller/controlplane/kcp_suite_test.go
tests/integration/controller/controlplane/kyma_remote_sync_test.go
tests/integration/controller/eventfilters/suite_test.go
tests/integration/controller/kyma/manifest_test.go
tests/integration/controller/kyma/suite_test.go
tests/integration/controller/mandatorymodules/suite_test.go
tests/integration/controller/withwatcher/suite_with_watcher_test.go
tests/integration/controller/withwatcher/watcher_certificate_test.go

- Move flags.go to internal/pkg
- Add unit tests for flags constants.
Resolves #1097

chore: Move flags.go to internal/pkg

---

api/v1beta2/moduletemplate_types.go
internal/tests/api/modulesync_test.go
tests/e2e/mandatory_module_test.go

- Dont sync ModuleTemplate if it is marked as mandatory

feat: Dont sync Deps if moduletemplate is mandatory

---

config/grafana/status.json

- Adding Kyma Warning and Module Warning to status dashboard

feat: Add Warning state to dashboard

---

pkg/remote/client_lookup.go
pkg/remote/cluster_client.go

- Add more logs to debug the no such host error on dev

chore: Add more logs to debug the no such host error on dev

---

internal/controller/kyma_controller.go
internal/controller/purge_controller.go
pkg/log/logger.go
pkg/remote/client_lookup.go

fix: Adjust log messages

---

pkg/remote/client_lookup.go
pkg/remote/cluster_client.go

fix: Display debug messages as Info level

---

internal/controller/purge_controller.go

- increase logging for the Purge Reconciler

chore: Debug logging for Purge Reconciler

---

.golangci.yaml

- keep Exhaustruct linter disabled
Closes #1014

chore: Add Explaination For Exhaustruct LInter Disabling

---

.github/workflows/verify-unit-test-coverage.yml
unit-test-coverage.yaml

- Adds a GitHub action as a quality gate for unit test coverage
[#1194](https://github.com/kyma-project/lifecycle-manager/issues/1194)

chore(SDLC, quality-gate): Adds a quality gate for a unit test coverage

---

scripts/migrator_cleanup.sh
scripts/storage_version_migrator.sh

- Adjust the context in the migrator script in order not to enforce it
#1119

fix: Adjust script based on SREs comments

---

internal/pkg/metrics/kyma.go

- Add a log message to ensure that the metrics cleanup job ran successfully

chore: Add log message for the metrics cleanup job

---

internal/declarative/v2/reconciler.go
pkg/util/error.go

- Improves the detection of connection errors as proposed in https://github.com/kyma-project/lifecycle-manager/pull/1275#discussion_r1481305436
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1236

chore: Improve detection of connection errors

---

.github/workflows/test-e2e.yml
internal/declarative/v2/reconciler.go
tests/e2e/warning_status_propagation_test.go

- Fix flapping module state
- Adjust the E2E test
#1080

fix: Fix flapping module state between Warning and Deleting

---

.github/workflows/create-release.yaml
scripts/release/create_changelog.sh
scripts/release/create_draft_release.sh
scripts/release/get_last_release.sh
scripts/release/get_release_by_tag.sh
scripts/release/publish_release.sh
scripts/release/validate_release_tag.sh
scripts/release/wait_for_image.sh

This PR adds the release workflow.
Note to the reviewer:
The workflow takes two input params: 
- tag name to create (must be a semver token)
- commit hash to tag or a branch name (the HEAD of the branch is then tagged)
- add release workflow
Resolves #1240

feat: Add release workflow

---

cmd/main.go
internal/controller/kyma_controller.go
internal/crd/cache.go
internal/crd/cache_test.go
pkg/remote/crd_upgrade.go
tests/integration/controller/controlplane/helper_test.go
tests/integration/controller/controlplane/kcp_suite_test.go
tests/integration/controller/eventfilters/suite_test.go
tests/integration/controller/kyma/suite_test.go
tests/integration/controller/withwatcher/suite_with_watcher_test.go
unit-test-coverage.yaml

- Extract global crd cache into testable struct
- Add tests and coverage
* https://github.com/kyma-project/lifecycle-manager/issues/1125

chore: Extract and test CRD caching

---

internal/declarative/v2/reconciler.go
internal/pkg/metrics/manifest.go
internal/pkg/metrics/metrics_test.go

- Record manifest reconciliation duration metric
Resolves #1069

feat: Manifest duration metrics

---

internal/declarative/v2/reconciler.go

- fixes the logging of `[manifest] got deleted!`
- we are logging this if any error occurred while getting the resource
- now we log it only if the error is a `NotFound` one
n/a

fix: Manifest got deleted log

---

internal/controller/purge_controller.go
internal/pkg/metrics/purge.go

- aligns log/error messages
- refactors the `Reconcile` function
- it is the "brains" for orchestrating the reconcile and delegates handling of certain situations to "handlers" now
- monitoring tasks (logs/metrics/events) have been taken out of the "helper" functions and promoted to the handlers
- it will be easier to see what is written for a given situation (e.g., sometimes we write logs in the helper functions but metrics/events in the outer function)
- adds new info level logs for when finalizers have been removed (either from Kyma or other resources)

chore: Refactor and increase purge controller monitoring

---

cmd/main.go

- the client.list in the storage version dropper sometimes throws this error "the cache is not started, can not read objects", that's why I added the wait for sync cache so that we wait for the cache to be initialized before we run the dropper.
Resolves #1383

fix: Add wait for cache sync for the storage version dropper

---

docs/developer-tutorials/local-test-setup.md
docs/modularization.md

- As agreed during a SIG-Content meeting, we should stick to using the "in cluster" instead of "on cluster" collocation
https://github.com/kyma-project/kyma/issues/18581

docs: IN cluster instead of ON

---

go.mod
go.sum

- replacement for late dependabot PR

deps: Upgrade controller-runtime to 0.17.3

---

internal/declarative/v2/reconciler.go

- Update Manifest LastOperation when an error occurs
Resolves #1453

fix: Update Manifest lastOperation when an error occurs

---

pkg/remote/kyma_synchronization_context.go

- Insert Istio SIdecar Injection Annotation
- Annotation is due to an incident now hardcoded
- Follow-up Issue will be created to clean this up: TBD

feat: Hardcode Istio Sidecar Injection Annotation

---

pkg/remote/kyma_synchronization_context.go

fix: Inject istio annotation

---

.github/actions/install-cmctl/action.yaml

- Fix installing cmctl action  (based on the documentation: [Fix installing cmctl action](https://cert-manager.io/docs/reference/cmctl/#manual-installation))

fix: Fix installing cmctl action

---

README.md
docs/user-tutorials/01-10-control-plane-quick-start.md

- Deprecate kyma provision k3d command
- https://github.com/kyma-project/kyma/issues/18652

refactor: Deprecate kyma provision k3d command

---

api/go.mod
api/go.sum
go.mod
go.sum

- supersedes: https://github.com/kyma-project/lifecycle-manager/pull/1531

deps: bump controller-runtime to v0.18.2

---

docs/technical-reference/architecture.md
docs/technical-reference/controllers.md

- ...
- ...
- ...
Closes #1150

docs: Purge Controller

---

docs/developer-tutorials/provision-cluster-and-registry.md

- Deprecate `kyma provision gardener`
- https://github.com/kyma-project/kyma/issues/18674

chore: Deprecate kyma provision gardener

---

docs/developer-tutorials/starting-operator-with-webhooks.md
docs/technical-reference/architecture.md

- The book.kubebuilder.io has been renamed to kubebuilder.io

fix: Kubebuilder links

---

docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md

- Kyma CLI deleted docs for commands

fix: Remove link to deleted doc

---

.github/workflows/check-api-changes.yaml

feat: add api changes checker pipeline

---

.github/workflows/check-api-changes.yaml

Feature/#1492 api changes GitHub actions

---

sec-scanners-config.yaml

- updates config to scan latest semver release

chore: Update protecode config to use version 1.0.0

---

config/grafana/mandatory-modules.json

Added Mandatory Modules dashboard to Plutono. Added panels/queries to view information on Warden mandatory module on the SKR(s).
Resolves #1468

feat: Add warden mandatory modules dashboard to plutono

---

config/grafana/kustomization.yaml

- we missed to add the new dashboard to kustomize. Hence, the Helm-based deployment did not generate the new chart.
- resolves https://github.com/kyma-project/lifecycle-manager/issues/1468

chore: Add mandatory-modules dashboard to kustomize

---

docs/user-tutorials/01-10-control-plane-quick-start.md

- fixing a link to make pipeline work again

chore: Fix broken Prometheus Quick Start link

---

.github/workflows/check-api-compatibility.yaml
.github/workflows/check-manifest-diffs.yaml
.github/workflows/lint-golangci.yml
.github/workflows/test-e2e.yaml
.github/workflows/test-smoke.yml
.github/workflows/test-unit.yml
.github/workflows/verify-unit-test-coverage.yml

- adds a pattern to also trigger GHA workflows for feature branches
- added to all workflows that were limiting on the branch

chore: Add `feat/**` as branch for PR-based Github Actions

---

api/v1beta2/kyma_types.go
config/crd/bases/operator.kyma-project.io_kymas.yaml
docs/technical-reference/api/kyma-cr.md
pkg/templatelookup/regular.go
tests/integration/controller/kyma/manifest_test.go

- Removed module referencing with NamespacedName
- Removed module referencing with FQDN
- Added tests for multiple module referencing scenarios
- Updated the documentation
Resolves #1521

feat: Drop multiple ways to reference modules in Kyma CR

---

.github/actions/deploy-template-operator/action.yaml
.github/workflows/test-e2e.yaml
internal/controller/manifest/controller.go
internal/declarative/v2/reconciler.go
internal/manifest/deployment_ready_check.go
internal/manifest/deployment_ready_check_test.go
internal/manifest/ready_check.go
internal/manifest/ready_check_test.go
internal/manifest/statefulset_ready_check.go
internal/manifest/statefulset_ready_check_test.go
pkg/testutils/modulecr.go
pkg/testutils/statefulset.go
tests/e2e/Makefile
tests/e2e/manifest_reconciliation_test.go
tests/e2e/module_consistency_test.go
tests/e2e/module_deletion_test.go
tests/e2e/module_status_decoupling_test.go
tests/e2e/module_status_decoupling_with_deployment_test.go
tests/e2e/module_status_decoupling_with_statefulset_test.go
tests/integration/controller/manifest/custom_resource_check/suite_test.go
tests/integration/controller/manifest/ready_check_test.go

- Support StatefulSet Module Resource in Ready Check
- Add E2E test
Resolves #1649

feat: Support StatefulSet Module Resource in Ready Check

---

.github/workflows/test-unit.yml
go.mod
go.sum

- bump golang.org/x/sync from 0.7.0 to 0.8.0

deps: bump golang.org/x/sync from 0.7.0 to 0.8.0

---

api/go.mod
api/go.sum
go.mod
go.sum

- Bump controller-runtime to v0.18.5

chore(deps): Bump Controller runtime

---

docs/technical-reference/api/changelog.md
docs/technical-reference/api/manifest-cr.md

chore: Improve document 

---

sec-scanners-config.yaml

Update security scanners config to version 1.1.3
- Update security scanners config

chore: Update security scanners config

---

.github/workflows/check-test-changes.yaml
tests/e2e/ca_certificate_rotation_test.go

This PR implement a github action to detect if there is any unit test (file with suffix `_test.go`) or integration, e2e test(file under `tests` folder) changes in the current PR, if there is no changes, failed the action to bring attention that certain tests is missing in this PR.
no test file detected: in this PR
test file change detect: https://github.com/kyma-project/lifecycle-manager/actions/runs/10580328047/job/29314903840?pr=1804

chore: Add check for test changes

---

internal/pkg/flags/flags.go
internal/pkg/flags/flags_test.go

related to: https://github.com/kyma-project/lifecycle-manager/issues/1410

chore: Remove drop-stored-version flag

---

internal/controller/kyma/controller.go
internal/controller/watcher/controller.go

- No error returned when kyma or watcher cr are in Unmanaged state, which is unsupported for both and should not happen

chore: Remove requeue on invalid cr state

---

config/manager/kustomization.yaml
internal/controller/manifest/controller.go
internal/manifest/keychain_provider.go
internal/manifest/parse.go
internal/manifest/spec_resolver.go
internal/manifest/spec_resolver_test.go
tests/integration/controller/manifest/custom_resource_check/suite_test.go
tests/integration/controller/manifest/suite_test.go
unit-test-coverage.yaml

Fixes: #1781 
- code refactor
- simple unit test
#1781

chore: Make spec_resolver.go testable

---

internal/manifest/statecheck/state_check.go
internal/manifest/statecheck/state_check_test.go

fix: Default no module manager found to state Ready

---

sec-scanners-config.yaml

- Bump lifecycle manager version in security scanners config

chore: Bump lifecycle manager version in security scanners config

---

api/shared/operator_labels.go
api/v1beta2/kyma_types.go
internal/declarative/v2/default_transforms.go
internal/declarative/v2/default_transforms_test.go
internal/remote/skr_context.go
pkg/module/common/module.go
pkg/module/common/module_test.go
pkg/testutils/builder/watcher.go
pkg/testutils/utils.go
pkg/watch/mandatory_template_change.go
pkg/watcher/certificate_manager.go
tests/integration/controller/mandatorymodule/deletion/controller_test.go
tests/integration/controller/mandatorymodule/installation/controller_test.go
tests/integration/controller/withwatcher/controller_test.go
tests/integration/controller/withwatcher/watcher_controller_helper_test.go

transparent Managedby label

---

.github/actions/setup-tools/action.yaml

- Somehow dependabot didn't pick up this usage

chore: Bump missing go setup action

---

config/watcher/kustomization.yaml
internal/pkg/flags/flags.go
skr-webhook/resources.yaml

- update watcher image to 1.1.6
- placeholder image tag to `latest` to reduce maintenance efforts and avoid confusion for image tag update
- remove `DefaultWatcherImageTag` to force the user configure image tag specifically 

chore: Update watcher image

---

.github/workflows/build-image.yml

the event name should be `workflow_dispatch`

fix: Build image event name

---

.github/actions/create-k3d-cluster/action.yml

Log the command used to create the k3d clusters to the console for better verbosity.
Resolves #1493

chore: Log cluster creation command to console

---

config/grafana/status.json

resolve the previously closed issue due to can't filter out Timestamp in table view, we should use `Instant` here to only query latest metrics.
https://github.com/kyma-project/lifecycle-manager/issues/1528

feat: Add Kyma Manifest in Error state for plutono dashboard 

---

sec-scanners-config.yaml

-  Add fields in security scanner config for checkmarxOne
Resolves #2029

feat: Add fields in security scanner config for checkmarxOne

---

tests/integration/controller/kcp/module_installation_test.go

chore: Use standard error lib in module_installation_test

---

config/watcher/kustomization.yaml

chore: Bump runtime-watcher to 1.1.8

---

sec-scanners-config.yaml

chore: Bump sec-scanners-config to 1.2.5

---

pkg/testutils/moduletemplate.go
tests/integration/controller/kcp/remote_sync_test.go

- fixes the Flaky remote_sync_test integration test
- makes the re-try on create module templates more robust
- in total, 5 consecutive executions succeeded now (previously we had roughly a 50/50 chance)

fix: Flaky remote_sync_test

---

docs/contributor/resources/03-moduletemplate.md
docs/contributor/resources/05-modulereleasemeta.md

- adds the docs for the moved internal/beta information.
- resolves https://github.com/kyma-project/lifecycle-manager/issues/2059

docs: Move `beta`/`internal` description from ModuleTemplate to ModuleReleaseMeta

---

api/v1beta1/moduletemplate_types.go
api/v1beta2/moduletemplate_types.go
config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
docs/contributor/resources/03-moduletemplate.md

feat: Add `spec.requiresDowntime`

---

sec-scanners-config.yaml

chore: Bump sec-scanners-config to 1.2.6

---

config/istio/kustomization.yaml
config/istio/patches/istio_deployment_labels.yaml
config/istio/patches/istio_namespace_labels.yaml

- Replace namespace istio injection with pod injection label
Resolves #1557

chore: Replace namespace istio injection with pod injection label

---

config/watcher/kustomization.yaml
sec-scanners-config.yaml

chore: Bump sec-scanners-config to 1.2.7 and use runtime-watcher 1.1.10

---

Dockerfile
api/go.mod
go.mod
maintenancewindows/go.mod
versions.yaml

Bump golang version.
**Changes proposed in this pull request:**
- Dockerfile
- go.mod
#2214

chore: Bump golang runtime version

---

.github/actions/deploy-lifecycle-manager-e2e/action.yml
cmd/main.go
config/watcher_local_test/kustomization.yaml
internal/maintenancewindows/maintenance_window.go
internal/maintenancewindows/maintenance_window_test.go
internal/pkg/flags/flags.go
internal/pkg/flags/flags_test.go

- Introduce KLM flag `min-maintenance-window-size`
- Mounts MWs for local testing
Closes #2222

chore: Use flag for min maintwindow size

---

config/watcher/kustomization.yaml
sec-scanners-config.yaml

chore: Bump sec-scanners config and rt-watcher version

---

.github/workflows/check-manifests-changes.yml
.github/workflows/test-e2e.yml

test: Test/pr manifest change alert

---

api/shared/operator_labels.go
api/v1beta2/kyma_types.go

- mapping was confirmed by gophers, todo can be removed
- https://github.com/kyma-project/kyma/issues/18611#issuecomment-2668116640

chore: Remove plan mapping TODO

---

.run/Launch KLM locally.run.xml
config/watcher/kustomization.yaml
sec-scanners-config.yaml

- Reference latest released version for bdba scanning
- Use latest runtime-watcher image

chore: Bump watcher version and scanner version to latest image

---

cmd/main.go
internal/pkg/flags/flags.go
internal/pkg/flags/flags_test.go

- added `--cert-management` flag
- added unit testing for this new flag
Resolves #2357

feat: Add `--cert-management` Flag

---

Dockerfile
api/go.mod
go.mod
maintenancewindows/go.mod
versions.yaml

- supersedes https://github.com/kyma-project/lifecycle-manager/pull/2379
- ...
- ...
- ...

chore: Bump golang from 1.24.1 to 1.24.2

---

sec-scanners-config.yaml

- Update sec-scanners-config.yaml with version 1.3.4

chore: Update sec-scanners-config.yaml

---

config/watcher/kustomization.yaml

chore: Bump skr-watcher-image to 1.1.15

---

config/samples/tests/test-configmap.yaml
internal/descriptor/cache/cache.go

chore: test secret

---

sec-scanners-config.yaml

- Bump lifecycle manager image to 1.3.6 in sec-scanners-config.yaml

chore: Bump lifecycle-manager image to 1.3.6 in sec-scanners-config.yaml

---

docs/contributor/adr/003-client-scope-and-usage.md
docs/contributor/adr/005-consistent-naming.md

- adds the ADR for consistent naming
- updates other ADR's examples to follow the consistent naming

docs: ADR 005 - Consistent Naming

---

README.md
docs/contributor/resources/README.md

- Added ModuleReleaseMeta to the `/docs/resources/README.md`
- Added ModuleReleaseMeta to the main `README.md`
- Updated the list of contributor docs in the main `README.md`

docs: Minor docu update

---

.github/scripts/release/create_changelog.sh
.run/Launch KLM locally.run.xml
config/watcher/kustomization.yaml
sec-scanners-config.yaml

- Update security scanner's config to latest
- Fix release changelog diff url generation
- Add runtime-watcher img latest

chore: Update sec scanner cfg & fix release diff

---

Dockerfile

chore: Fix args for new image-builder

---

.github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
.github/actions/deploy-template-operator/action.yml
scripts/tests/deploy_moduletemplate.sh
tests/e2e/utils_test.go
versions.yaml

- Bump modulectl version to 1.2.2

chore: Bump modulectl version to 1.2.2

---

.github/workflows/scorecard.yml

Introduce [OpenSSF Scorecard](https://github.com/ossf/scorecard) to KLM.

chore: Introduce OpenSSF scorecard

---

.run/Launch KLM locally.run.xml
config/watcher/kustomization.yaml

chore: Update runtime-watcher image tag to 1.2.0

---

tests/e2e/legacy_istio_gateway_secret_rotation_cm_test.go
tests/e2e/legacy_istio_gateway_secret_rotation_gcm_test.go

Based on the review comment: https://github.com/kyma-project/lifecycle-manager/pull/2582/files#r2206904093
https://github.com/kyma-project/lifecycle-manager/issues/2436

chore: Check test against expected cert manager

---

.github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
.github/actions/deploy-template-operator/action.yml

- Reduced the liveness and readiness probe values
- Reduced the progressDeadlineSeconds to 60s.
Resolves #2606

fix: Improve module-status-decoupling-with-deployment E2E test

---

sec-scanners-config.yaml

chore: Set sec-scanner-cfg bdba tag to next release 1.5.2

---

config/watcher/kustomization.yaml

chore: Update skr-watcher-image-tag to version 2.0.1

---

.github/workflows/lint-golangci.yml
Makefile

- use binary install for golangci-lint instead of source install
- supersedes https://github.com/kyma-project/lifecycle-manager/pull/2748

chore: Use binary install for golangci-lint

---

sec-scanners-config.yaml

chore: Bump sec scanners image to 1.7.1
